# Generated by Django 5.2.17 on 2026-09-23 01:52

import app_center.documents.backend.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0011_retire_contacts'),
        ('conversations', '0001_initial_compacted'),
        ('enterprise', '0007_compacted_0007_0008'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='未命名文档', max_length=200)),
                ('content', models.JSONField(default=app_center.documents.backend.models.empty_content)),
                ('plain_text', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'online_documents',
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', '只读'), ('editor', '编辑')], max_length=10)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='online_documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_session', to='conversations.conversation')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='online_documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'application', 'owner'], name='documents_scope'),
        ),
        migrations.AddConstraint(
            model_name='documentgrant',
            constraint=models.UniqueConstraint(fields=('document', 'user'), name='document_user_grant'),
        ),
        migrations.AddConstraint(
            model_name='documentsession',
            constraint=models.UniqueConstraint(fields=('document', 'user'), name='document_user_session'),
        ),
    ]
