# Generated by Django 5.2.17 on 2026-09-24 08:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0011_retire_contacts'),
        ('enterprise', '0008_membership_monthly_token_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('positioning', models.JSONField(blank=True, default=dict)),
                ('voice', models.JSONField(blank=True, default=dict)),
                ('visual', models.JSONField(blank=True, default=dict)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brand_library_profiles',
                'ordering': ['-updated_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('facts', models.JSONField(blank=True, default=list)),
                ('source', models.TextField(blank=True)),
                ('restrictions', models.TextField(blank=True)),
                ('prohibited_claims', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='brand_library.brandprofile')),
            ],
            options={
                'db_table': 'brand_library_products',
                'ordering': ['-updated_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('highlights', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='brand_library.brandprofile')),
            ],
            options={
                'db_table': 'brand_library_examples',
                'ordering': ['-updated_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='brandprofile',
            index=models.Index(fields=['organization', 'application', 'owner'], name='brand_profile_scope'),
        ),
    ]
