# Generated by Django 5.2.17 on 2026-09-18 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('projects', '0001_initial'), ('projects', '0002_projectasset_content_alter_projectasset_url'), ('projects', '0003_project_organization'), ('projects', '0004_projectasset_file')]

    dependencies = [
        ('enterprise', '0001_initial'),
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('structure', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('completed', '已完成'), ('archived', '已归档')], default='draft', max_length=20)),
                ('thumbnail', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='templates.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='enterprise.organization')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('video', '视频'), ('audio', '音频'), ('image', '图片'), ('text', '文本'), ('other', '其他')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.project')),
                ('content', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, upload_to='project_assets/%Y/%m/')),
            ],
            options={
                'db_table': 'project_assets',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
