# Generated by Django 5.2.17 on 2026-09-18 12:56

import django.db.migrations.operations.special
import django.db.models.deletion
from importlib import import_module
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.projects.migrations.0006_backfill_project_application
# apps.projects.migrations.0008_project_workflow_project_project_has_single_origin
# apps.projects.migrations.0009_require_project_organization

_backfill_application = import_module(
    "apps.projects.migrations.0006_backfill_project_application"
)
_workflow_origins = import_module(
    "apps.projects.migrations.0008_project_workflow_project_project_has_single_origin"
)
_project_orgs = import_module(
    "apps.projects.migrations.0009_require_project_organization"
)

class Migration(migrations.Migration):

    atomic = False

    replaces = [('projects', '0006_backfill_project_application'), ('projects', '0007_remove_project_template'), ('projects', '0008_project_workflow_project_project_has_single_origin'), ('projects', '0009_require_project_organization')]

    dependencies = [
        ('applications', '0006_chat_application_subtype'),
        ('conversations', '0003_conversation_working_directory'),
        ('enterprise', '0005_external_identity'),
        ('projects', '0005_project_application_project_working_directory'),
        ('workflows', '0004_workflow_dag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            code=_backfill_application.backfill_project_application,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='project',
            name='template',
        ),
        migrations.AddField(
            model_name='project',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='workflows.workflow'),
        ),
        migrations.RunPython(
            code=_workflow_origins.migrate_workflow_origins,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('application__isnull', True), ('workflow__isnull', True), _connector='OR'), name='project_has_single_origin'),
        ),
        migrations.RunPython(
            code=_project_orgs.backfill_project_organizations,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='enterprise.organization'),
        ),
    ]
