# Generated by Django 5.2.17 on 2026-09-30 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_personal_form_presets'),
        ('enterprise', '0008_membership_monthly_token_limit'),
        ('projects', '0006_compacted_0006_0009'),
        ('workflows', '0007_workflow_input_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='directory_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='directory_source',
            field=models.CharField(choices=[('managed', '自动分配'), ('explicit', '显式绑定')], default='managed', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='scope',
            field=models.CharField(choices=[('default', '默认'), ('cowork', 'CoWork')], db_index=True, default='default', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'cowork')), fields=('organization', 'user', 'directory_key'), name='unique_cowork_directory'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'cowork'), _negated=True), models.Q(('application__isnull', True), ('directory_source', 'explicit'), ('workflow__isnull', True), models.Q(('directory_key', ''), _negated=True), models.Q(('working_directory', ''), _negated=True)), _connector='OR'), name='cowork_requires_directory'),
        ),
    ]
