# Generated by Django 5.2.17 on 2026-09-18 12:56

import django.db.migrations.operations.special
from importlib import import_module
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.workflows.migrations.0004_workflow_dag

_workflow_dag = import_module("apps.workflows.migrations.0004_workflow_dag")

class Migration(migrations.Migration):

    atomic = False

    replaces = [('workflows', '0003_remove_workflowsteprun_workflow_run_and_more'), ('workflows', '0004_workflow_dag'), ('workflows', '0005_workflow_execution_mode'), ('workflows', '0006_workflow_output_mapping')]

    dependencies = [
        ('conversations', '0005_remove_parallel_execution_models'),
        ('workflows', '0002_working_directories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowsteprun',
            name='workflow_run',
        ),
        migrations.RemoveField(
            model_name='workflowsteprun',
            name='application',
        ),
        migrations.RemoveField(
            model_name='workflowsteprun',
            name='workflow_step',
        ),
        migrations.DeleteModel(
            name='WorkflowRun',
        ),
        migrations.DeleteModel(
            name='WorkflowStepRun',
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='key',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='depends_on',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='condition',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RunPython(
            code=_workflow_dag.convert_ordered_steps,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='workflowstep',
            constraint=models.UniqueConstraint(fields=('workflow', 'key'), name='unique_workflow_step_key'),
        ),
        migrations.AddConstraint(
            model_name='workflowstep',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='workflow_step_attempts_at_least_one'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='execution_mode',
            field=models.CharField(choices=[('manual', '手动执行'), ('automatic', '自动执行')], default='automatic', max_length=20),
        ),
        migrations.AddField(
            model_name='workflow',
            name='output_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
