# Generated by Django 5.0.1 on 2026-09-11 10:45

import hashlib
import json

import django.db.models.deletion
from django.db import migrations, models


def _content_hash(content):
    encoded = json.dumps(
        content, ensure_ascii=False, sort_keys=True,
        separators=(',', ':'),
    ).encode('utf-8')
    return hashlib.sha256(encoded).hexdigest()


def pin_existing_step_runs(apps, schema_editor):
    WorkflowStepRun = apps.get_model('workflows', 'WorkflowStepRun')
    ApplicationDraft = apps.get_model('catalog', 'ApplicationDraft')
    ApplicationRevision = apps.get_model('catalog', 'ApplicationRevision')
    ApplicationDeployment = apps.get_model(
        'catalog', 'ApplicationDeployment')
    ChatApplicationRevision = apps.get_model(
        'catalog', 'ChatApplicationRevision')

    for step_run in WorkflowStepRun.objects.select_related(
            'application').all().iterator():
        application = step_run.application
        deployment = ApplicationDeployment.objects.filter(
            application_id=application.id,
            environment='production',
        ).first()
        revision = deployment.revision if deployment is not None else None
        if revision is None:
            revision = ApplicationRevision.objects.filter(
                application_id=application.id).order_by('-revision_no').first()
        if revision is None:
            draft = ApplicationDraft.objects.filter(
                application_id=application.id).first()
            if draft is None:
                raise RuntimeError(
                    f'Application {application.id} has no definition to pin')
            digest = _content_hash(draft.content)
            revision = ApplicationRevision.objects.filter(
                application_id=application.id,
                content_hash=digest,
            ).first()
            if revision is None:
                revision = ApplicationRevision.objects.create(
                    organization_id=application.organization_id,
                    application_id=application.id,
                    revision_no=1,
                    schema_version=1,
                    content=draft.content,
                    content_hash=digest,
                    release_notes='Pinned automatically for an existing workflow run.',
                    created_by_id=application.created_by_id,
                )
        if application.kind == 'chat':
            ChatApplicationRevision.objects.get_or_create(revision_id=revision.id)
        WorkflowStepRun.objects.filter(pk=step_run.pk).update(
            application_revision_id=revision.id)


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_chatapplication_and_more'),
        ('catalog', '0003_chatapplicationrevision'),
        ('workflows', '0002_working_directories'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowsteprun',
            name='application_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_step_runs', to='catalog.applicationrevision'),
        ),
        migrations.RunPython(
            pin_existing_step_runs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='workflowsteprun',
            name='application_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_step_runs', to='catalog.applicationrevision'),
        ),
    ]
