# Generated by Django 5.0.1 on 2026-09-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_remove_parallel_execution_models'),
        ('workflows', '0002_working_directories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowsteprun',
            name='workflow_run',
        ),
        migrations.RemoveField(
            model_name='workflowsteprun',
            name='application',
        ),
        migrations.RemoveField(
            model_name='workflowsteprun',
            name='workflow_step',
        ),
        migrations.DeleteModel(
            name='WorkflowRun',
        ),
        migrations.DeleteModel(
            name='WorkflowStepRun',
        ),
    ]
