# Generated by Django 5.2.17 on 2026-09-18 12:54

import django.db.migrations.operations.special
import django.db.models.deletion
import uuid
from importlib import import_module
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# modules.execution.migrations.0002_postgresql_rls
# modules.execution.migrations.0005_run_queue_entry

_rls = import_module("modules.execution.migrations.0002_postgresql_rls")
_queue = import_module("modules.execution.migrations.0005_run_queue_entry")

class Migration(migrations.Migration):

    atomic = False

    replaces = [('execution', '0001_initial'), ('execution', '0002_postgresql_rls'), ('execution', '0003_run_hierarchy'), ('execution', '0004_run_waiting_children'), ('execution', '0005_run_queue_entry')]

    dependencies = [
        ('enterprise', '0005_external_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executor_kind', models.CharField(choices=[('agent', 'Agent'), ('media', 'Media'), ('workflow', 'Workflow'), ('evaluation', 'Evaluation')], db_index=True, max_length=20)),
                ('executor_key', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('source_type', models.CharField(db_index=True, max_length=80)),
                ('source_id', models.CharField(blank=True, default='', max_length=160)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('waiting_input', 'Waiting for input'), ('cancelling', 'Cancelling'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('priority', models.SmallIntegerField(db_index=True, default=0)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('next_event_sequence', models.PositiveBigIntegerField(default=0)),
                ('next_lease_epoch', models.PositiveBigIntegerField(default=0)),
                ('retry_safe', models.BooleanField(default=True)),
                ('definition_snapshot', models.JSONField(default=dict)),
                ('input', models.JSONField(default=dict)),
                ('output_summary', models.JSONField(blank=True, default=dict)),
                ('pending_input_request_id', models.UUIDField(blank=True, null=True)),
                ('pending_input_kind', models.CharField(blank=True, choices=[('answer', 'Answer'), ('permission', 'Permission')], default='', max_length=20)),
                ('pending_input_expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'runs',
                'ordering': ('-priority', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RunArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(db_index=True, max_length=50)),
                ('object_key', models.CharField(max_length=500)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('mime_type', models.CharField(max_length=160)),
                ('size', models.PositiveBigIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='execution.run')),
            ],
            options={
                'db_table': 'run_artifacts',
            },
        ),
        migrations.CreateModel(
            name='RunAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('running', 'Running'), ('suspended', 'Suspended'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('interrupted', 'Interrupted'), ('cancelled', 'Cancelled')], db_index=True, default='claimed', max_length=20)),
                ('worker_pool', models.CharField(db_index=True, max_length=40)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('checkpoint_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='execution.runartifact')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='execution.run')),
            ],
            options={
                'db_table': 'run_attempts',
                'ordering': ('run_id', 'attempt_no'),
            },
        ),
        migrations.AddField(
            model_name='runartifact',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='execution.runattempt'),
        ),
        migrations.AddField(
            model_name='run',
            name='current_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='execution.runattempt'),
        ),
        migrations.CreateModel(
            name='RunCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('answer', 'Answer'), ('grant_permission', 'Grant permission'), ('deny_permission', 'Deny permission'), ('cancel', 'Cancel')], max_length=30)),
                ('input_request_id', models.UUIDField(blank=True, null=True)),
                ('expected_run_version', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_commands', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='execution.run')),
            ],
            options={
                'db_table': 'run_commands',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RunEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField()),
                ('type', models.CharField(db_index=True, max_length=100)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='execution.runattempt')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='execution.run')),
            ],
            options={
                'db_table': 'run_events',
                'ordering': ('run_id', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='RunEventSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('through_sequence', models.PositiveBigIntegerField()),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('projection', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_snapshot', to='execution.run')),
            ],
            options={
                'db_table': 'run_event_snapshots',
            },
        ),
        migrations.CreateModel(
            name='RunLease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worker_id', models.CharField(db_index=True, max_length=160)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('epoch', models.PositiveBigIntegerField()),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('heartbeat_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lease', to='execution.runattempt')),
            ],
            options={
                'db_table': 'run_leases',
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=160)),
                ('key', models.CharField(max_length=160)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
            ],
            options={
                'db_table': 'idempotency_records',
                'constraints': [models.UniqueConstraint(fields=('organization', 'actor', 'operation', 'key'), name='unique_idempotency_scope')],
            },
        ),
        migrations.AddConstraint(
            model_name='runattempt',
            constraint=models.UniqueConstraint(fields=('run', 'attempt_no'), name='unique_run_attempt_number'),
        ),
        migrations.AddConstraint(
            model_name='runattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('finished_at__isnull', True)), fields=('run',), name='one_active_attempt_per_run'),
        ),
        migrations.AddConstraint(
            model_name='runartifact',
            constraint=models.UniqueConstraint(fields=('run', 'object_key', 'content_hash'), name='unique_run_artifact_content'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['executor_kind', 'status', '-priority', 'created_at'], name='run_claim_idx'),
        ),
        migrations.AddConstraint(
            model_name='run',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='run_max_attempts_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='run',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pending_input_expires_at__isnull', False), ('pending_input_kind__in', ('answer', 'permission')), ('pending_input_request_id__isnull', False), ('status', 'waiting_input')), models.Q(models.Q(('status', 'waiting_input'), _negated=True), ('pending_input_request_id__isnull', True), ('pending_input_kind', ''), ('pending_input_expires_at__isnull', True)), _connector='OR'), name='run_pending_input_consistent'),
        ),
        migrations.AddConstraint(
            model_name='runcommand',
            constraint=models.UniqueConstraint(fields=('organization', 'created_by', 'type', 'idempotency_key'), name='unique_run_command_idempotency'),
        ),
        migrations.AddIndex(
            model_name='runevent',
            index=models.Index(fields=['run', 'sequence'], name='run_event_cursor_idx'),
        ),
        migrations.AddConstraint(
            model_name='runevent',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='unique_run_event_sequence'),
        ),
        migrations.AddConstraint(
            model_name='runeventsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('through_sequence__gte', 1)), name='run_snapshot_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='runlease',
            constraint=models.UniqueConstraint(fields=('attempt', 'epoch'), name='unique_attempt_lease_epoch'),
        ),
        migrations.RunPython(
            code=_rls.enable_rls,
            reverse_code=_rls.disable_rls,
        ),
        migrations.AddField(
            model_name='run',
            name='node_key',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='run',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_runs', to='execution.run'),
        ),
        migrations.AddConstraint(
            model_name='run',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'node_key'), name='unique_child_run_node_key'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['parent', 'status'], name='run_parent_status_idx'),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('waiting_input', 'Waiting for input'), ('waiting_children', 'Waiting for child runs'), ('cancelling', 'Cancelling'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20),
        ),
        migrations.CreateModel(
            name='RunQueueEntry',
            fields=[
                ('organization_id', models.UUIDField(db_index=True)),
                ('worker_pool', models.CharField(db_index=True, max_length=20)),
                ('executor_key', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('priority', models.SmallIntegerField(default=0)),
                ('enqueued_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='queue_entry', serialize=False, to='execution.run')),
            ],
            options={
                'db_table': 'run_queue_entries',
                'ordering': ('-priority', 'enqueued_at', 'run_id'),
                'indexes': [models.Index(fields=['worker_pool', '-priority', 'enqueued_at'], name='run_queue_claim_idx')],
            },
        ),
        migrations.RunPython(
            code=_queue.backfill_queue,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
