# Generated by Django 5.0.1 for the destructive V2 schema baseline.
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("v2_tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("operation", models.CharField(max_length=160)),
                ("key", models.CharField(max_length=160)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("status", models.CharField(choices=[("processing", "Processing"), ("completed", "Completed"), ("failed", "Failed")], default="processing", max_length=20)),
                ("response_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="v2_idempotency_records", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="v2_tenancy.organization")),
            ],
            options={"db_table": "v2_idempotency_records"},
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("executor_kind", models.CharField(choices=[("agent", "Agent"), ("media", "Media"), ("workflow", "Workflow"), ("evaluation", "Evaluation")], db_index=True, max_length=20)),
                ("source_type", models.CharField(db_index=True, max_length=80)),
                ("source_id", models.CharField(blank=True, default="", max_length=160)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("waiting_input", "Waiting for input"), ("cancelling", "Cancelling"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("cancelled", "Cancelled")], db_index=True, default="queued", max_length=20)),
                ("priority", models.SmallIntegerField(db_index=True, default=0)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("version", models.PositiveBigIntegerField(default=0)),
                ("next_event_sequence", models.PositiveBigIntegerField(default=0)),
                ("next_lease_epoch", models.PositiveBigIntegerField(default=0)),
                ("retry_safe", models.BooleanField(default=True)),
                ("definition_snapshot", models.JSONField(default=dict)),
                ("input", models.JSONField(default=dict)),
                ("output_summary", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, default="", max_length=100)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="v2_tenancy.organization")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="v2_runs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "v2_runs", "ordering": ("-priority", "created_at", "id")},
        ),
        migrations.CreateModel(
            name="RunAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("attempt_no", models.PositiveIntegerField()),
                ("status", models.CharField(choices=[("claimed", "Claimed"), ("running", "Running"), ("suspended", "Suspended"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("interrupted", "Interrupted"), ("cancelled", "Cancelled")], db_index=True, default="claimed", max_length=20)),
                ("worker_pool", models.CharField(db_index=True, max_length=40)),
                ("checkpoint_object_key", models.CharField(blank=True, default="", max_length=500)),
                ("error_code", models.CharField(blank=True, default="", max_length=100)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="v2_execution.run")),
            ],
            options={"db_table": "v2_run_attempts", "ordering": ("run_id", "attempt_no")},
        ),
        migrations.CreateModel(
            name="RunArtifact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(db_index=True, max_length=50)),
                ("object_key", models.CharField(max_length=500)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("mime_type", models.CharField(max_length=160)),
                ("size", models.PositiveBigIntegerField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("attempt", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="artifacts", to="v2_execution.runattempt")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="v2_tenancy.organization")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="artifacts", to="v2_execution.run")),
            ],
            options={"db_table": "v2_run_artifacts"},
        ),
        migrations.AddField(
            model_name="run",
            name="current_attempt",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="v2_execution.runattempt"),
        ),
        migrations.CreateModel(
            name="RunCommand",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("type", models.CharField(choices=[("answer", "Answer"), ("grant_permission", "Grant permission"), ("deny_permission", "Deny permission"), ("cancel", "Cancel")], max_length=30)),
                ("input_request_id", models.UUIDField(blank=True, null=True)),
                ("expected_run_version", models.PositiveBigIntegerField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("idempotency_key", models.CharField(max_length=160)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="v2_run_commands", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="v2_tenancy.organization")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="commands", to="v2_execution.run")),
            ],
            options={"db_table": "v2_run_commands", "ordering": ("created_at", "id")},
        ),
        migrations.CreateModel(
            name="RunEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sequence", models.PositiveBigIntegerField()),
                ("type", models.CharField(db_index=True, max_length=100)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("attempt", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="events", to="v2_execution.runattempt")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="v2_tenancy.organization")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="v2_execution.run")),
            ],
            options={"db_table": "v2_run_events", "ordering": ("run_id", "sequence")},
        ),
        migrations.CreateModel(
            name="RunLease",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("worker_id", models.CharField(db_index=True, max_length=160)),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("epoch", models.PositiveBigIntegerField()),
                ("acquired_at", models.DateTimeField(auto_now_add=True)),
                ("heartbeat_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("attempt", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="lease", to="v2_execution.runattempt")),
            ],
            options={"db_table": "v2_run_leases"},
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.UniqueConstraint(fields=("organization", "actor", "operation", "key"), name="v2_unique_idempotency_scope"),
        ),
        migrations.AddConstraint(
            model_name="runattempt",
            constraint=models.UniqueConstraint(fields=("run", "attempt_no"), name="v2_unique_run_attempt_number"),
        ),
        migrations.AddConstraint(
            model_name="runartifact",
            constraint=models.UniqueConstraint(fields=("run", "object_key", "content_hash"), name="v2_unique_run_artifact_content"),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["executor_kind", "status", "-priority", "created_at"], name="v2_run_claim_idx"),
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.CheckConstraint(check=models.Q(("max_attempts__gte", 1)), name="v2_run_max_attempts_at_least_one"),
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.CheckConstraint(check=models.Q(("attempt_count__lte", models.F("max_attempts"))), name="v2_run_attempts_within_limit"),
        ),
        migrations.AddConstraint(
            model_name="runcommand",
            constraint=models.UniqueConstraint(fields=("organization", "created_by", "type", "idempotency_key"), name="v2_unique_run_command_idempotency"),
        ),
        migrations.AddIndex(
            model_name="runevent",
            index=models.Index(fields=["run", "sequence"], name="v2_run_event_cursor_idx"),
        ),
        migrations.AddConstraint(
            model_name="runevent",
            constraint=models.UniqueConstraint(fields=("run", "sequence"), name="v2_unique_run_event_sequence"),
        ),
        migrations.AddConstraint(
            model_name="runlease",
            constraint=models.UniqueConstraint(fields=("attempt", "epoch"), name="v2_unique_attempt_lease_epoch"),
        ),
    ]
