#!/usr/bin/env python
"""Build the Windows desktop distribution with offline license login enabled."""

from __future__ import annotations

import argparse
import base64
import binascii
import os
from pathlib import Path

import build_desktop


BACKEND_ROOT = Path(__file__).resolve().parent


def parser() -> argparse.ArgumentParser:
    command = argparse.ArgumentParser(
        description="Build Agent Studio with machine-bound offline licensing.",
    )
    command.add_argument(
        "--public-key",
        type=Path,
        default=BACKEND_ROOT / "license-public.key",
        help="Ed25519 public-key file generated by license_generator.py",
    )
    command.add_argument(
        "--product-id",
        default="agent-studio",
        help="Product identifier embedded in the app and issued licenses",
    )
    return command


def read_public_key(path: Path) -> str:
    resolved = path.expanduser().resolve()
    if not resolved.is_file():
        raise SystemExit(
            f"Public key not found: {resolved}\n"
            "Generate it first with: python tools/license_generator.py generate-keys"
        )
    value = resolved.read_text(encoding="utf-8").strip()
    if not value:
        raise SystemExit(f"Public key is empty: {resolved}")
    try:
        raw_key = base64.urlsafe_b64decode(value + "=" * (-len(value) % 4))
    except (ValueError, binascii.Error) as exc:
        raise SystemExit(f"Public key encoding is invalid: {resolved}") from exc
    if len(raw_key) != 32:
        raise SystemExit(f"Public key must decode to 32 bytes: {resolved}")
    return value


def main() -> None:
    args = parser().parse_args()
    product_id = args.product_id.strip()
    if not product_id:
        raise SystemExit("--product-id cannot be empty")

    os.environ["LICENSE_AUTH_ENABLED"] = "True"
    os.environ["LICENSE_PUBLIC_KEY"] = read_public_key(args.public_key)
    os.environ["LICENSE_PRODUCT_ID"] = product_id

    print(f"License mode: enabled ({product_id})")
    print(f"Public key:  {args.public_key.expanduser().resolve()}")
    build_desktop.build()


if __name__ == "__main__":
    main()
