# Generated by Django 5.2.17 on 2026-09-18 12:47

import app_center.creation_toolbox.backend.models
import django.db.models.deletion
import uuid
from importlib import import_module
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# app_center.creation_toolbox.backend.migrations.0002_postgresql_rls

_rls = import_module(
    "app_center.creation_toolbox.backend.migrations.0002_postgresql_rls"
)

class Migration(migrations.Migration):

    replaces = [('creation_toolbox', '0001_initial'), ('creation_toolbox', '0002_postgresql_rls')]

    initial = True

    dependencies = [
        ('applications', '0007_generalize_default_experience'),
        ('enterprise', '0008_remove_knowledgedocument_knowledge_base_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreationWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='创作工具箱', max_length=120)),
                ('storage_mode', models.CharField(default='managed', max_length=32)),
                ('audio_sample_rate', models.PositiveIntegerField(default=44100)),
                ('transcription_language', models.CharField(default='zh-CN', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creation_toolbox_workspace', to='applications.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
            ],
            options={
                'db_table': 'creation_toolbox_workspaces',
            },
        ),
        migrations.CreateModel(
            name='CreationProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creation_projects', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='creation_toolbox.creationworkspace')),
            ],
            options={
                'db_table': 'creation_toolbox_projects',
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Copywriting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('style', models.CharField(choices=[('funny', '搞笑'), ('emotional', '情感'), ('informative', '干货'), ('science', '科普'), ('marketing', '营销')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creation_copywritings', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copywritings', to='creation_toolbox.creationproject')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copywritings', to='creation_toolbox.creationworkspace')),
            ],
            options={
                'db_table': 'creation_toolbox_copywritings',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='creation_toolbox.materialfolder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='creation_toolbox.creationproject')),
            ],
            options={
                'db_table': 'creation_toolbox_folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=500, upload_to=app_center.creation_toolbox.backend.models.asset_upload_path)),
                ('kind', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('audio', '音频'), ('document', '文档'), ('other', '其他')], default='other', max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creation_assets', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='creation_toolbox.materialfolder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='creation_toolbox.creationproject')),
            ],
            options={
                'db_table': 'creation_toolbox_assets',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('audio', models.FileField(max_length=500, upload_to=app_center.creation_toolbox.backend.models.recording_upload_path)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('transcription', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creation_recordings', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='creation_toolbox.creationproject')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='creation_toolbox.creationworkspace')),
            ],
            options={
                'db_table': 'creation_toolbox_recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creation_scripts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scripts', to='creation_toolbox.creationproject')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='creation_toolbox.creationworkspace')),
            ],
            options={
                'db_table': 'creation_toolbox_scripts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenes', to='creation_toolbox.mediaasset')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='creation_toolbox.script')),
            ],
            options={
                'db_table': 'creation_toolbox_scenes',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='creationproject',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_creation_project_name'),
        ),
        migrations.AddConstraint(
            model_name='materialfolder',
            constraint=models.UniqueConstraint(fields=('project', 'parent', 'name'), name='unique_creation_folder_name'),
        ),
        migrations.AddConstraint(
            model_name='scene',
            constraint=models.UniqueConstraint(fields=('script', 'order'), name='unique_scene_order'),
        ),
        migrations.RunPython(
            code=_rls.enable_rls,
            reverse_code=_rls.disable_rls,
        ),
    ]
