# Generated by Django 5.2.17 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creation_toolbox", "0003_full_creation_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="creationproject",
            name="work_type",
            field=models.CharField(
                choices=[
                    ("image_text", "图文"),
                    ("long_article", "长图文（公众号）"),
                    ("short_video", "短视频"),
                ],
                db_index=True,
                default="short_video",
                max_length=24,
            ),
        ),
    ]
