# Generated by Django 5.2.17 on 2026-09-20 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation_toolbox', '0004_creationproject_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicidea',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='creation_toolbox.topicidea'),
        ),
    ]
