from django.urls import path

from . import views


urlpatterns = [
    path("applications/<int:application_id>/creation-toolbox/workspace", views.WorkspaceView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/topics", views.TopicListView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/topics/bulk", views.TopicBulkUpdateView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/topics/tags", views.TopicTagsView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/topics/<uuid:topic_id>", views.TopicDetailView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/topics/<uuid:topic_id>/create-project", views.TopicCreateProjectView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/projects", views.ProjectListView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/projects/<uuid:project_id>", views.ProjectDetailView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/projects/<uuid:project_id>/archive", views.ProjectArchiveView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/projects/<uuid:project_id>/stage-transitions", views.ProjectStageTransitionView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/projects/<uuid:project_id>/folders", views.FolderListView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/projects/<uuid:project_id>/folders/<uuid:folder_id>", views.FolderDetailView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/projects/<uuid:project_id>/assets", views.AssetListView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/projects/<uuid:project_id>/assets/<uuid:asset_id>", views.AssetDetailView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/recordings", views.RecordingListView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/recordings/<uuid:recording_id>", views.RecordingDetailView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/recordings/<uuid:recording_id>/transcribe", views.RecordingTranscribeView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/copywritings", views.CopywritingListView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/copywritings/<uuid:copywriting_id>", views.CopywritingDetailView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/scripts", views.ScriptListView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/scripts/<uuid:script_id>", views.ScriptDetailView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/scripts/<uuid:script_id>/scenes", views.SceneListView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/scripts/<uuid:script_id>/scenes/reorder", views.SceneReorderView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/scripts/<uuid:script_id>/scenes/<uuid:scene_id>", views.SceneDetailView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/scripts/<uuid:script_id>/export", views.ScriptExportView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/deliverables", views.DeliverableListView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/deliverables/<uuid:deliverable_id>", views.DeliverableDetailView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/publications", views.PublicationListView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/publications/<uuid:publication_id>", views.PublicationDetailView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/publications/<uuid:publication_id>/metrics", views.MetricSnapshotListView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/publications/<uuid:publication_id>/metrics/<uuid:snapshot_id>", views.MetricSnapshotDetailView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/analytics", views.AnalyticsView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/metrics-csv/template", views.MetricsCsvTemplateView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/metrics-csv/import", views.MetricsCsvImportView.as_view()),
    path("applications/<int:application_id>/creation-toolbox/metrics-csv/export", views.MetricsCsvExportView.as_view()),
]
