# Generated by Django 5.0.1 on 2026-09-11 05:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0004_remove_agentdeployment_agent_and_more'),
        ('applications', '0004_application_is_active_alter_application_slug_and_more'),
        ('enterprise', '0005_external_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.JSONField(default=dict)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='agents.agent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_drafts',
            },
        ),
        migrations.CreateModel(
            name='AgentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_no', models.PositiveIntegerField()),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('content', models.JSONField(default=dict)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('release_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='agents.agent')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
            ],
            options={
                'db_table': 'agent_revisions',
                'ordering': ('agent_id', 'revision_no'),
            },
        ),
        migrations.CreateModel(
            name='AgentDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], max_length=20)),
                ('config_override', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='agents.agent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_deployments', to='catalog.agentrevision')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='catalog.agentrevision')),
            ],
            options={
                'db_table': 'agent_deployments',
            },
        ),
        migrations.CreateModel(
            name='ApplicationDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.JSONField(default=dict)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='applications.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application_drafts',
            },
        ),
        migrations.CreateModel(
            name='ApplicationRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_no', models.PositiveIntegerField()),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('content', models.JSONField(default=dict)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('release_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='applications.application')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
            ],
            options={
                'db_table': 'application_revisions',
                'ordering': ('application_id', 'revision_no'),
            },
        ),
        migrations.CreateModel(
            name='ApplicationDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], max_length=20)),
                ('config_override', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='applications.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_deployments', to='catalog.applicationrevision')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='catalog.applicationrevision')),
            ],
            options={
                'db_table': 'application_deployments',
            },
        ),
        migrations.CreateModel(
            name='SkillDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.JSONField(default=dict)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='applications.skill')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skill_drafts',
            },
        ),
        migrations.CreateModel(
            name='SkillRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_no', models.PositiveIntegerField()),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('content', models.JSONField(default=dict)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('release_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='applications.skill')),
            ],
            options={
                'db_table': 'skill_revisions',
                'ordering': ('skill_id', 'revision_no'),
            },
        ),
        migrations.AddConstraint(
            model_name='agentrevision',
            constraint=models.UniqueConstraint(fields=('agent', 'revision_no'), name='unique_agent_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='agentrevision',
            constraint=models.UniqueConstraint(fields=('agent', 'content_hash'), name='unique_agent_revision_content'),
        ),
        migrations.AddConstraint(
            model_name='agentdeployment',
            constraint=models.UniqueConstraint(fields=('agent', 'environment'), name='unique_agent_deployment_environment'),
        ),
        migrations.AddConstraint(
            model_name='applicationrevision',
            constraint=models.UniqueConstraint(fields=('application', 'revision_no'), name='unique_application_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='applicationrevision',
            constraint=models.UniqueConstraint(fields=('application', 'content_hash'), name='unique_application_revision_content'),
        ),
        migrations.AddConstraint(
            model_name='applicationdeployment',
            constraint=models.UniqueConstraint(fields=('application', 'environment'), name='unique_application_deployment_environment'),
        ),
        migrations.AddConstraint(
            model_name='skillrevision',
            constraint=models.UniqueConstraint(fields=('skill', 'revision_no'), name='unique_skill_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='skillrevision',
            constraint=models.UniqueConstraint(fields=('skill', 'content_hash'), name='unique_skill_revision_content'),
        ),
    ]
