# Generated by Django 5.2.17 on 2026-09-18 12:53

import django.db.migrations.operations.special
import django.db.models.deletion
import uuid
from importlib import import_module
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# modules.catalog.migrations.0002_database_guards
# modules.catalog.migrations.0003_chatapplicationrevision
# modules.catalog.migrations.0004_deploy_seeded_general_agent
# modules.catalog.migrations.0005_skill_deployment
# modules.catalog.migrations.0006_backfill_skill_drafts

_guards = import_module("modules.catalog.migrations.0002_database_guards")
_chat_revision = import_module(
    "modules.catalog.migrations.0003_chatapplicationrevision"
)
_deploy_general = import_module(
    "modules.catalog.migrations.0004_deploy_seeded_general_agent"
)
_skill_deployment = import_module("modules.catalog.migrations.0005_skill_deployment")
_skill_drafts = import_module("modules.catalog.migrations.0006_backfill_skill_drafts")

class Migration(migrations.Migration):

    atomic = False

    replaces = [('catalog', '0002_database_guards'), ('catalog', '0003_chatapplicationrevision'), ('catalog', '0004_deploy_seeded_general_agent'), ('catalog', '0005_skill_deployment'), ('catalog', '0006_backfill_skill_drafts')]

    dependencies = [
        ('agents', '0006_move_agent_definition_to_catalog'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            code=_guards.install_guards,
            reverse_code=_guards.remove_guards,
        ),
        migrations.CreateModel(
            name='ChatApplicationRevision',
            fields=[
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chat_revision', serialize=False, to='catalog.applicationrevision')),
            ],
            options={
                'db_table': 'chat_application_revisions',
            },
        ),
        migrations.RunPython(
            code=_chat_revision.create_chat_revision_subtypes,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=_deploy_general.deploy_seeded_general_agent,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name='SkillDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], max_length=20)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_deployments', to='catalog.skillrevision')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='catalog.skillrevision')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='applications.skill')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skill_deployments',
                'constraints': [models.UniqueConstraint(fields=('skill', 'environment'), name='unique_skill_deployment_environment')],
            },
        ),
        migrations.RunPython(
            code=_skill_deployment.install_rls,
            reverse_code=_skill_deployment.remove_rls,
        ),
        migrations.RunPython(
            code=_skill_drafts.create_missing_skill_drafts,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
