# Generated by Django 5.0.1 on 2026-09-11 10:45

import django.db.models.deletion
from django.db import migrations, models


def create_chat_revision_subtypes(apps, schema_editor):
    ApplicationRevision = apps.get_model('catalog', 'ApplicationRevision')
    ChatApplicationRevision = apps.get_model(
        'catalog', 'ChatApplicationRevision')
    ChatApplicationRevision.objects.bulk_create([
        ChatApplicationRevision(revision_id=revision_id)
        for revision_id in ApplicationRevision.objects.filter(
            application__kind='chat').values_list('id', flat=True)
    ], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_database_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatApplicationRevision',
            fields=[
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chat_revision', serialize=False, to='catalog.applicationrevision')),
            ],
            options={
                'db_table': 'chat_application_revisions',
            },
        ),
        migrations.RunPython(
            create_chat_revision_subtypes, migrations.RunPython.noop),
    ]
