# Generated by Django 5.2.17 on 2026-09-17 03:11

from django.conf import settings
from django.db import migrations, models


def collapse_environment_deployments(apps, schema_editor):
    """Keep one legacy deployment per resource before adding unique constraints."""

    priority = {"development": 1, "staging": 2, "production": 3}
    database = schema_editor.connection.alias
    deployment_models = (
        ("AgentDeployment", "agent_id"),
        ("ApplicationDeployment", "application_id"),
        ("SkillDeployment", "skill_id"),
    )

    for model_name, resource_field in deployment_models:
        model = apps.get_model("catalog", model_name)
        selected = {}
        discarded = []
        for deployment in model.objects.using(database).all():
            resource_id = getattr(deployment, resource_field)
            current = selected.get(resource_id)
            candidate_rank = (
                priority.get(deployment.environment, 0),
                deployment.version,
            )
            if current is None:
                selected[resource_id] = deployment
                continue
            current_rank = (
                priority.get(current.environment, 0),
                current.version,
            )
            if candidate_rank > current_rank:
                discarded.append(current.pk)
                selected[resource_id] = deployment
            else:
                discarded.append(deployment.pk)

        if discarded:
            model.objects.using(database).filter(pk__in=discarded).delete()


class Migration(migrations.Migration):

    # PostgreSQL may retain deferred trigger events after the data cleanup;
    # subsequent ALTER TABLE operations must run outside that transaction.
    atomic = False

    dependencies = [
        ('agents', '0007_agent_kind_supervisor_profile'),
        ('applications', '0007_generalize_default_experience'),
        ('catalog', '0006_backfill_skill_drafts'),
        ('enterprise', '0008_remove_knowledgedocument_knowledge_base_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            collapse_environment_deployments,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='agentdeployment',
            name='unique_agent_deployment_environment',
        ),
        migrations.RemoveConstraint(
            model_name='applicationdeployment',
            name='unique_application_deployment_environment',
        ),
        migrations.RemoveConstraint(
            model_name='skilldeployment',
            name='unique_skill_deployment_environment',
        ),
        migrations.RemoveField(
            model_name='agentdeployment',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='applicationdeployment',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='skilldeployment',
            name='environment',
        ),
        migrations.AddConstraint(
            model_name='agentdeployment',
            constraint=models.UniqueConstraint(fields=('agent',), name='unique_agent_deployment'),
        ),
        migrations.AddConstraint(
            model_name='applicationdeployment',
            constraint=models.UniqueConstraint(fields=('application',), name='unique_application_deployment'),
        ),
        migrations.AddConstraint(
            model_name='skilldeployment',
            constraint=models.UniqueConstraint(fields=('skill',), name='unique_skill_deployment'),
        ),
    ]
