# Generated by Django 5.2.17 on 2026-09-18 06:58

import apps.users.models
from django.db import migrations


def align_superuser_roles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(is_superuser=True).exclude(role='admin').update(role='admin')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_creator_role_to_member'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
        migrations.RunPython(align_superuser_roles, migrations.RunPython.noop),
    ]
