# Generated by Django 5.2.17 on 2026-09-18 12:58

import django.db.migrations.operations.special
import django.db.models.deletion
from importlib import import_module
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.agents.migrations.0003_seed_general_agent

_seed_general = import_module("apps.agents.migrations.0003_seed_general_agent")

class Migration(migrations.Migration):

    replaces = [('agents', '0002_initial'), ('agents', '0003_seed_general_agent')]

    dependencies = [
        ('agents', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentskillbinding',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_bindings', to='applications.skill'),
        ),
        migrations.AddConstraint(
            model_name='agentdeployment',
            constraint=models.UniqueConstraint(fields=('agent', 'environment'), name='unique_agent_environment'),
        ),
        migrations.AddConstraint(
            model_name='agentskillbinding',
            constraint=models.UniqueConstraint(fields=('agent', 'skill'), name='unique_agent_skill_binding'),
        ),
        migrations.RunPython(
            code=_seed_general.seed_general_agent,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
