# Generated by Django 5.0.1 on 2026-09-11 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_seed_general_agent'),
        ('enterprise', '0005_external_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_agent_slug_per_org'),
        ),
        migrations.DeleteModel(name='AgentDeployment'),
    ]
