# Generated by Django 5.0.1 on 2026-09-11 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_remove_agentdeployment_agent_and_more'),
        ('enterprise', '0005_external_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentexecution',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agentexecution',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('slug',), name='unique_global_agent_slug'),
        ),
        migrations.DeleteModel(
            name='AgentExecution',
        ),
    ]
