# Generated by Django 5.2.17 on 2026-09-18 12:59

import django.db.migrations.operations.special
from importlib import import_module
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.agents.migrations.0006_move_agent_definition_to_catalog

_move_definitions = import_module(
    "apps.agents.migrations.0006_move_agent_definition_to_catalog"
)

class Migration(migrations.Migration):

    atomic = False

    replaces = [('agents', '0005_remove_agentexecution_agent_and_more'), ('agents', '0006_move_agent_definition_to_catalog')]

    dependencies = [
        ('agents', '0004_remove_agentdeployment_agent_and_more'),
        ('applications', '0004_application_is_active_alter_application_slug_and_more'),
        ('catalog', '0001_initial'),
        ('enterprise', '0005_external_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentexecution',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agentexecution',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('slug',), name='unique_global_agent_slug'),
        ),
        migrations.DeleteModel(
            name='AgentExecution',
        ),
        migrations.RunPython(
            code=_move_definitions.migrate_agent_definitions,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='agent',
            name='guardrail_config',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='knowledge_config',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='model_config',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_config',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='system_prompt',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='tool_config',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='workflow_config',
        ),
        migrations.DeleteModel(
            name='AgentSkillBinding',
        ),
    ]
