# Generated by Django 5.0.1 on 2026-09-11 10:45

from django.db import migrations
from django.utils.text import slugify


def _owner_organization(apps, owner):
    Organization = apps.get_model('enterprise', 'Organization')
    Membership = apps.get_model('enterprise', 'Membership')
    QuotaPolicy = apps.get_model('enterprise', 'QuotaPolicy')
    GovernancePolicy = apps.get_model('enterprise', 'GovernancePolicy')

    membership = Membership.objects.filter(
        user_id=owner.id, is_active=True).order_by('id').first()
    if membership is not None:
        return Organization.objects.get(pk=membership.organization_id)
    organization = Organization.objects.filter(owner_id=owner.id).order_by(
        'created_at').first()
    if organization is None:
        base = slugify(owner.username)[:70] or f'user-{owner.pk}'
        organization, _ = Organization.objects.get_or_create(
            slug=f'{base}-{owner.pk}',
            defaults={'name': f'{owner.username} Workspace', 'owner_id': owner.id},
        )
    Membership.objects.get_or_create(
        organization_id=organization.id, user_id=owner.id,
        defaults={'role': 'owner', 'is_active': True},
    )
    QuotaPolicy.objects.get_or_create(organization_id=organization.id)
    GovernancePolicy.objects.get_or_create(organization_id=organization.id)
    return organization


def migrate_agent_definitions(apps, schema_editor):
    Agent = apps.get_model('agents', 'Agent')
    AgentDraft = apps.get_model('catalog', 'AgentDraft')
    AgentSkillBinding = apps.get_model('agents', 'AgentSkillBinding')

    for agent in Agent.objects.select_related('created_by').all().iterator():
        organization_id = agent.organization_id
        if organization_id is None:
            organization = _owner_organization(apps, agent.created_by)
            organization_id = organization.id
            Agent.objects.filter(pk=agent.pk).update(
                organization_id=organization_id)

        bindings = [
            {
                'skill_id': str(binding.skill_id),
                'mode': binding.mode,
                'config': binding.config,
                'order': binding.order,
            }
            for binding in AgentSkillBinding.objects.filter(
                agent_id=agent.id).order_by('order', 'id')
        ]
        if not bindings:
            for order, item in enumerate(agent.skill_config or []):
                if not isinstance(item, dict) or not item.get('skill_id'):
                    continue
                bindings.append({
                    'skill_id': str(item['skill_id']),
                    'mode': item.get('mode', 'default'),
                    'config': item.get('config', {}),
                    'order': item.get('order', order),
                })

        draft, _ = AgentDraft.objects.get_or_create(
            agent_id=agent.id,
            defaults={
                'organization_id': organization_id,
                'updated_by_id': agent.created_by_id,
                'content': {
                    'system_prompt': agent.system_prompt,
                    'model_config': agent.model_config,
                    'tool_config': agent.tool_config,
                    'knowledge_config': agent.knowledge_config,
                    'guardrail_config': agent.guardrail_config,
                    'workflow_config': agent.workflow_config,
                    'skill_bindings': bindings,
                },
            },
        )


class Migration(migrations.Migration):
    # PostgreSQL cannot drop the legacy columns while deferred foreign-key
    # trigger events from the data copy are pending in the same transaction.
    # Commit each operation independently so the data copy is durable before
    # the schema cleanup begins.
    atomic = False

    dependencies = [
        ('agents', '0005_remove_agentexecution_agent_and_more'),
        ('applications', '0004_application_is_active_alter_application_slug_and_more'),
        ('catalog', '0001_initial'),
        ('enterprise', '0005_external_identity'),
    ]

    operations = [
        migrations.RunPython(
            migrate_agent_definitions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='agent',
            name='guardrail_config',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='knowledge_config',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='model_config',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='skill_config',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='system_prompt',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='tool_config',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='workflow_config',
        ),
        migrations.DeleteModel(
            name='AgentSkillBinding',
        ),
    ]
