# Generated by Django 5.2.17 on 2026-09-18 12:52

import django.db.migrations.operations.special
import django.db.models.deletion
from importlib import import_module
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.agents.migrations.0008_publish_initial_agent_versions

_publish_versions = import_module(
    "apps.agents.migrations.0008_publish_initial_agent_versions"
)

class Migration(migrations.Migration):

    atomic = False

    replaces = [('agents', '0008_publish_initial_agent_versions'), ('agents', '0009_active_agent_slug_constraints'), ('agents', '0010_agent_access_scope_agent_allowed_users')]

    dependencies = [
        ('agents', '0007_agent_kind_supervisor_profile'),
        ('catalog', '0007_single_active_deployment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            code=_publish_versions.publish_initial_agent_versions,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='agent',
            name='unique_agent_slug_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='agent',
            name='unique_global_agent_slug',
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization', 'slug'), name='unique_agent_slug_per_org'),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('organization__isnull', True)), fields=('slug',), name='unique_global_agent_slug'),
        ),
        migrations.AddField(
            model_name='agent',
            name='visibility',
            field=models.CharField(choices=[('private', '仅创建者'), ('restricted', '指定账号'), ('organization', '组织内全部账号')], db_index=True, default='private', max_length=20),
        ),
        migrations.CreateModel(
            name='AgentAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', '查看者'), ('user', '使用者'), ('operator', '运维者'), ('editor', '编辑者')], default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='agents.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_access_grants',
                'constraints': [models.UniqueConstraint(fields=('agent', 'user'), name='unique_agent_access_grant')],
            },
        ),
    ]
