# Generated by Django 5.2.17 on 2026-09-18 12:52

import django.db.migrations.operations.special
from importlib import import_module
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.agents.migrations.0008_publish_initial_agent_versions

_publish_versions = import_module(
    "apps.agents.migrations.0008_publish_initial_agent_versions"
)

class Migration(migrations.Migration):

    atomic = False

    replaces = [('agents', '0008_publish_initial_agent_versions'), ('agents', '0009_active_agent_slug_constraints'), ('agents', '0010_agent_access_scope_agent_allowed_users')]

    dependencies = [
        ('agents', '0007_agent_kind_supervisor_profile'),
        ('catalog', '0007_single_active_deployment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            code=_publish_versions.publish_initial_agent_versions,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='agent',
            name='unique_agent_slug_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='agent',
            name='unique_global_agent_slug',
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization', 'slug'), name='unique_agent_slug_per_org'),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('organization__isnull', True)), fields=('slug',), name='unique_global_agent_slug'),
        ),
        migrations.AddField(
            model_name='agent',
            name='access_scope',
            field=models.CharField(choices=[('admin', '仅管理员'), ('restricted', '指定账号'), ('organization', '组织内全部账号')], db_index=True, default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='agent',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_agents', to=settings.AUTH_USER_MODEL),
        ),
    ]
