# Generated by Django 5.2.17 on 2026-09-29 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation_studio', '0002_postgresql_rls'),
        ('applications', '0012_personal_form_presets'),
        ('enterprise', '0008_membership_monthly_token_limit'),
        ('execution', '0008_run_command_steer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animationasset',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animationasset',
            name='category',
            field=models.CharField(default='素材', max_length=40),
        ),
        migrations.CreateModel(
            name='AnimationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rows', models.JSONField(default=list)),
                ('template', models.JSONField(default=dict)),
                ('export_options', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('run', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='execution.run')),
            ],
            options={
                'db_table': 'animation_studio_batches',
            },
        ),
        migrations.CreateModel(
            name='AnimationPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('template', '模板'), ('brand', '品牌')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'animation_studio_presets',
            },
        ),
        migrations.CreateModel(
            name='AnimationProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='未命名作品', max_length=200)),
                ('archived', models.BooleanField(default=False)),
                ('draft', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'animation_studio_projects',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AnimationSpeechConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(blank=True, max_length=200)),
                ('resource_id', models.CharField(default='seed-tts-2.0', max_length=200)),
                ('secret_ref', models.CharField(blank=True, max_length=200)),
                ('voices', models.JSONField(default=list)),
                ('enabled', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
            ],
            options={
                'db_table': 'animation_studio_speech',
            },
        ),
        migrations.CreateModel(
            name='AnimationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.JSONField(default=dict)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='animation_studio.animationproject')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='animation_version', to='execution.run')),
            ],
            options={
                'db_table': 'animation_studio_versions',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
