# Generated by Django 5.2.17 on 2026-09-24 08:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0011_retire_contacts'),
        ('enterprise', '0008_membership_monthly_token_limit'),
        ('execution', '0006_compacted_0006_0007'),
        ('knowledge', '0002_knowledgebase_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('objective', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cleanup_pending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('knowledge_base', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='knowledge.knowledgebase')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResearchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=30)),
                ('instruction', models.TextField(blank=True)),
                ('objective', models.TextField()),
                ('source_snapshot', models.JSONField(default=list)),
                ('request_key', models.CharField(max_length=160)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='research_assistant.researchproject')),
                ('run', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='execution.run')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResearchExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160)),
                ('request_hash', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=20)),
                ('response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='research_assistant.researchresult')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.JSONField(default=dict)),
                ('removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='knowledge.knowledgedocument')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='research_assistant.researchproject')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['organization', 'application', 'owner'], name='research_as_organiz_f3f2cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='researchresult',
            constraint=models.UniqueConstraint(fields=('project', 'request_key'), name='research_generation_key'),
        ),
        migrations.AddConstraint(
            model_name='researchexport',
            constraint=models.UniqueConstraint(fields=('result', 'key'), name='research_export_key'),
        ),
    ]
