# Generated by Django 5.2.17 on 2026-09-27 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0007_compacted_0007_0008'),
        ('kitchen_assistant', '0002_postgresql_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen_assistant.kitchenstate')),
            ],
            options={
                'db_table': 'kitchen_assistant_operation',
                'constraints': [models.UniqueConstraint(fields=('state', 'operation_id'), name='kitchen_operation_identity')],
            },
        ),
        migrations.CreateModel(
            name='KitchenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=200)),
                ('data', models.JSONField(default=dict)),
                ('finished_at', models.DateTimeField()),
                ('revision', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='kitchen_assistant.kitchenstate')),
            ],
            options={
                'db_table': 'kitchen_assistant_record',
                'indexes': [models.Index(fields=['state', '-finished_at', 'id'], name='kitchen_record_page')],
                'constraints': [models.UniqueConstraint(fields=('state', 'record_id'), name='kitchen_record_identity')],
            },
        ),
    ]
