# Generated by Django 5.2.17 on 2026-09-27 05:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


def enable_rls(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('ALTER TABLE kitchen_assistant_ai_task ENABLE ROW LEVEL SECURITY')
            cursor.execute('ALTER TABLE kitchen_assistant_ai_task FORCE ROW LEVEL SECURITY')
            cursor.execute("CREATE POLICY tenant_isolation ON kitchen_assistant_ai_task "
                           "USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid) "
                           "WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid)")


def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('DROP POLICY IF EXISTS tenant_isolation ON kitchen_assistant_ai_task')
            cursor.execute('ALTER TABLE kitchen_assistant_ai_task DISABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0008_membership_monthly_token_limit'),
        ('execution', '0006_compacted_0006_0007'),
        ('kitchen_assistant', '0004_history_data_and_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenAITask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('instruction', models.TextField()),
                ('request_key', models.CharField(max_length=160)),
                ('request_hash', models.CharField(max_length=64)),
                ('revision', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('run', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='execution.run')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to='kitchen_assistant.kitchenstate')),
            ],
            options={
                'db_table': 'kitchen_assistant_ai_task',
                'ordering': ['-created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('state', 'request_key'), name='kitchen_ai_request_key')],
            },
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
