# Generated by Django 5.2.17 on 2026-09-27 05:28

from django.db import migrations, models


def backfill_names(apps, schema_editor):
    Record = apps.get_model("kitchen_assistant", "KitchenRecord")
    Organization = apps.get_model("enterprise", "Organization")
    with schema_editor.connection.cursor() as cursor:
        previous = None
        if schema_editor.connection.vendor == "postgresql":
            cursor.execute("SELECT current_setting('app.organization_id', true)")
            previous = cursor.fetchone()[0] or ""
        try:
            for organization_id in Organization.objects.values_list("id", flat=True).iterator():
                if previous is not None:
                    cursor.execute("SELECT set_config('app.organization_id', %s, true)", [str(organization_id)])
                for record in Record.objects.filter(organization_id=organization_id).iterator():
                    record.recipe_names = "\n".join(record.data.get("recipeNames", []))
                    record.save(update_fields=["recipe_names"])
        finally:
            if previous is not None:
                cursor.execute("SELECT set_config('app.organization_id', %s, true)", [previous])


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_assistant', '0005_kitchenaitask'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenrecord',
            name='recipe_names',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(backfill_names, migrations.RunPython.noop),
    ]
