# Generated by Django 5.2.17 on 2026-09-30 06:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0012_personal_form_presets'),
        ('enterprise', '0008_membership_monthly_token_limit'),
        ('execution', '0008_run_command_steer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('mode', models.CharField(default='generate', max_length=16)),
                ('topic', models.TextField(blank=True)),
                ('original', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('scene', models.CharField(default='auto', max_length=20)),
                ('detected_scene', models.CharField(default='general', max_length=20)),
                ('language', models.CharField(default='zh', max_length=8)),
                ('questions', models.JSONField(default=list)),
                ('answers', models.JSONField(default=dict)),
                ('analysis', models.JSONField(default=dict)),
                ('rounds', models.PositiveSmallIntegerField(default=0)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('results_stale', models.BooleanField(default=False)),
                ('favorite', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prompt_master_session',
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PromptTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=16)),
                ('request_key', models.CharField(max_length=160)),
                ('request_hash', models.CharField(max_length=64)),
                ('revision', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('run', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='execution.run')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='prompt_master.promptsession')),
            ],
            options={
                'db_table': 'prompt_master_task',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=16)),
                ('standard', models.TextField()),
                ('concise', models.TextField()),
                ('assumptions', models.JSONField(default=list)),
                ('health', models.JSONField(default=list)),
                ('changes', models.JSONField(default=list)),
                ('constraints', models.JSONField(default=list)),
                ('health_stale', models.BooleanField(default=False)),
                ('basis', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='prompt_master.promptsession')),
            ],
            options={
                'db_table': 'prompt_master_version',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='promptsession',
            index=models.Index(fields=['organization', 'owner', 'application', '-updated_at'], name='prompt_private_history'),
        ),
        migrations.AddConstraint(
            model_name='prompttask',
            constraint=models.UniqueConstraint(fields=('session', 'request_key'), name='prompt_task_request_key'),
        ),
    ]
