# Generated by Django 5.2.17 on 2026-09-23 01:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0008_compacted_0008_0010'),
        ('applications', '0011_retire_contacts'),
        ('conversations', '0001_initial_compacted'),
        ('enterprise', '0007_compacted_0007_0008'),
        ('execution', '0006_compacted_0006_0007'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('peer_id', models.CharField(blank=True, max_length=255)),
                ('credentials', models.TextField(blank=True)),
                ('status', models.CharField(default='unbound', max_length=32)),
                ('enabled', models.BooleanField(default=False)),
                ('generation', models.UUIDField(default=uuid.uuid4)),
                ('cursor', models.TextField(blank=True)),
                ('login_id', models.UUIDField(blank=True, null=True)),
                ('login_data', models.TextField(blank=True)),
                ('login_expires_at', models.DateTimeField(blank=True, null=True)),
                ('lease_owner', models.CharField(blank=True, max_length=64)),
                ('lease_until', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_poll_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversations.conversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wechat_assistant_bindings',
            },
        ),
        migrations.CreateModel(
            name='IncomingMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation', models.UUIDField()),
                ('message_id', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('context_token', models.TextField(blank=True)),
                ('supported', models.BooleanField(default=True)),
                ('state', models.CharField(default='pending', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='wechat_assistant.binding')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversations.conversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.organization')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='execution.run')),
            ],
            options={
                'db_table': 'wechat_assistant_incoming',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=100)),
                ('part', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('state', models.CharField(default='pending', max_length=24)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incoming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='wechat_assistant.incomingmessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.organization')),
            ],
            options={
                'db_table': 'wechat_assistant_outgoing',
                'ordering': ['created_at', 'part'],
            },
        ),
        migrations.AddConstraint(
            model_name='binding',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='wechat_binding_user_org'),
        ),
        migrations.AddConstraint(
            model_name='incomingmessage',
            constraint=models.UniqueConstraint(fields=('binding', 'message_id'), name='wechat_incoming_unique'),
        ),
        migrations.AddConstraint(
            model_name='outgoingmessage',
            constraint=models.UniqueConstraint(fields=('incoming', 'event_key', 'part'), name='wechat_outgoing_unique'),
        ),
    ]
