# Generated by Django 5.2.17 on 2026-09-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_assistant', '0002_postgresql_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='binding',
            name='menu_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='binding',
            name='menu_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='binding',
            name='menu_state',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
