# Generated by Django 5.2.17 on 2026-09-18 12:46

import apps.conversations.models
import django.db.migrations.operations.special
import django.db.models.deletion
import uuid
from importlib import import_module
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.conversations.migrations.0006_require_organization_and_message_run
# apps.conversations.migrations.0007_chat_application_context
# apps.conversations.migrations.0010_clear_implicit_general_agent
# apps.conversations.migrations.0011_backfill_supervisor_agent_conversations

_require_org = import_module(
    "apps.conversations.migrations.0006_require_organization_and_message_run"
)
_chat_context = import_module(
    "apps.conversations.migrations.0007_chat_application_context"
)
_clear_general = import_module(
    "apps.conversations.migrations.0010_clear_implicit_general_agent"
)
_backfill_supervisor = import_module(
    "apps.conversations.migrations.0011_backfill_supervisor_agent_conversations"
)

class Migration(migrations.Migration):

    atomic = False

    replaces = [('conversations', '0001_initial'), ('conversations', '0002_initial'), ('conversations', '0003_conversation_working_directory'), ('conversations', '0004_agentthread_agentturn_agentserverrequest_agentitem_and_more'), ('conversations', '0005_remove_parallel_execution_models'), ('conversations', '0006_require_organization_and_message_run'), ('conversations', '0007_chat_application_context'), ('conversations', '0008_conversation_agent_thread'), ('conversations', '0009_message_run_events'), ('conversations', '0010_clear_implicit_general_agent'), ('conversations', '0011_backfill_supervisor_agent_conversations'), ('conversations', '0012_messageattachment'), ('conversations', '0013_conversation_agent_locked')]

    initial = True

    dependencies = [
        ('agents', '0002_initial'),
        ('applications', '0001_initial'),
        ('applications', '0006_chat_application_subtype'),
        ('enterprise', '0001_initial'),
        ('enterprise', '0005_external_identity'),
        ('execution', '0002_postgresql_rls'),
        ('projects', '0004_projectasset_file'),
        ('workflows', '0001_initial'),
        ('workflows', '0002_working_directories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('process_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='agents.agent')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='applications.application')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='enterprise.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('workflow_step_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='workflows.workflowsteprun')),
                ('working_directory', models.CharField(blank=True, default='', max_length=1000)),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手'), ('system', '系统')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationSkillBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('agent_required', '智能体必需'), ('agent_default', '智能体默认'), ('app_required', '应用必需'), ('app_default', '应用默认'), ('user', '用户选择')], max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_bindings', to='conversations.conversation')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_bindings', to='applications.skill')),
            ],
            options={
                'db_table': 'conversation_skill_bindings',
                'constraints': [models.UniqueConstraint(fields=('conversation', 'skill'), name='unique_conversation_skill_binding')],
            },
        ),
        migrations.CreateModel(
            name='AgentThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='graphflow', max_length=32)),
                ('remote_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('active', 'Active'), ('archived', 'Archived'), ('error', 'Error')], default='idle', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_thread', to='conversations.conversation')),
            ],
            options={
                'db_table': 'agent_threads',
            },
        ),
        migrations.CreateModel(
            name='AgentTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('interrupted', 'Interrupted')], default='pending', max_length=20)),
                ('input', models.JSONField(blank=True, default=list)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='conversations.agentthread')),
            ],
            options={
                'db_table': 'agent_turns',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentServerRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.CharField(blank=True, default='', max_length=255)),
                ('method', models.CharField(max_length=128)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_requests', to='conversations.agentthread')),
                ('turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_requests', to='conversations.agentturn')),
            ],
            options={
                'db_table': 'agent_server_requests',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=64)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('content', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='conversations.agentturn')),
            ],
            options={
                'db_table': 'agent_items',
                'ordering': ['ordinal', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentthread',
            index=models.Index(fields=['provider', 'remote_id'], name='agent_threa_provide_0fd9f3_idx'),
        ),
        migrations.AddIndex(
            model_name='agentturn',
            index=models.Index(fields=['thread', 'status'], name='agent_turns_thread__9e43c4_idx'),
        ),
        migrations.AddIndex(
            model_name='agentserverrequest',
            index=models.Index(fields=['thread', 'status'], name='agent_serve_thread__4b49e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentitem',
            constraint=models.UniqueConstraint(fields=('turn', 'remote_id'), name='unique_agent_item_remote_id'),
        ),
        migrations.AddConstraint(
            model_name='agentserverrequest',
            constraint=models.UniqueConstraint(fields=('thread', 'turn', 'remote_id', 'method'), name='unique_agent_server_request_remote_id'),
        ),
        migrations.DeleteModel(
            name='AgentServerRequest',
        ),
        migrations.DeleteModel(
            name='AgentItem',
        ),
        migrations.DeleteModel(
            name='AgentTurn',
        ),
        migrations.DeleteModel(
            name='AgentThread',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='workflow_step_run',
        ),
        migrations.RunPython(
            code=_require_org.remove_unscoped_conversations,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='enterprise.organization'),
        ),
        migrations.AddField(
            model_name='message',
            name='run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projected_message', to='execution.run'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='chat_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='applications.chatapplication'),
        ),
        migrations.RunPython(
            code=_chat_context.preserve_chat_context_and_memberships,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='application',
        ),
        migrations.AddField(
            model_name='conversation',
            name='agent_thread_provider',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='conversation',
            name='agent_thread_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agent_thread_id', ''), ('agent_thread_provider', '')), models.Q(models.Q(('agent_thread_provider', ''), _negated=True), models.Q(('agent_thread_id', ''), _negated=True)), _connector='OR'), name='conversation_agent_thread_consistent'),
        ),
        migrations.AlterField(
            model_name='message',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projected_messages', to='execution.run'),
        ),
        migrations.AddField(
            model_name='message',
            name='run_event_sequence',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('run__isnull', False), ('run_event_sequence__isnull', False)), fields=('run', 'run_event_sequence'), name='unique_run_event_message'),
        ),
        migrations.RunPython(
            code=_clear_general.clear_implicit_general_agent,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=_backfill_supervisor.backfill_supervisor_agent_conversations,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=apps.conversations.models.message_attachment_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='conversations.conversation')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='conversations.message')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_attachments', to='enterprise.organization')),
            ],
            options={
                'db_table': 'message_attachments',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['conversation', 'message'], name='message_att_convers_c98bce_idx')],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='agent_locked',
            field=models.BooleanField(default=False),
        ),
    ]
