# Generated by Django 5.2.17 on 2026-09-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial_compacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='scope',
            field=models.CharField(choices=[('default', '默认'), ('cowork', 'CoWork')], db_index=True, default='default', max_length=20),
        ),
    ]
