# Generated by Django 5.0.1 on 2026-09-11 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_standalone_chat_context(apps, schema_editor):
    Conversation = apps.get_model('conversations', 'Conversation')
    ChatApplication = apps.get_model('applications', 'ChatApplication')
    chat_application_ids = set(
        ChatApplication.objects.values_list('application_id', flat=True))
    for conversation in Conversation.objects.filter(
            workflow_step_run__isnull=True,
            application_id__in=chat_application_ids).iterator():
        Conversation.objects.filter(pk=conversation.pk).update(
            chat_application_id=conversation.application_id)


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_remove_agent_guardrail_config_and_more'),
        ('applications', '0005_chatapplication_and_more'),
        ('conversations', '0004_agentthread_agentturn_agentserverrequest_agentitem_and_more'),
        ('enterprise', '0005_external_identity'),
        ('projects', '0007_remove_project_template'),
        ('workflows', '0003_workflowsteprun_application_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='chat_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='applications.chatapplication'),
        ),
        migrations.RunPython(
            preserve_standalone_chat_context, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='conversation',
            name='application',
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(check=models.Q(('chat_application__isnull', True), ('workflow_step_run__isnull', True), _connector='OR'), name='conversation_has_no_duplicate_chat_context'),
        ),
    ]
