# Generated by Django 5.2.17 on 2026-09-17 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0008_remove_knowledgedocument_knowledge_base_and_more'),
        ('execution', '0005_run_queue_entry'),
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgedocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='knowledgechunk',
            name='unique_document_chunk_position',
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='answer_model',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='answer_provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='lexical_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chunks', to='enterprise.organization'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='section_path',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='active_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='byte_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='error_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='indexing_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indexed_knowledge_documents', to='execution.run'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='mime_type',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to='enterprise.organization'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='pending_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='source_object_key',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='chunk_overlap',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='chunk_size',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='source_type',
            field=models.CharField(choices=[('text', 'Text'), ('upload', 'Upload')], default='text', max_length=30),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('indexing', 'Indexing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['document', 'revision', 'position'], name='knowledge_c_documen_87b7d3_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['organization', 'revision'], name='knowledge_c_organiz_8f284c_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['knowledge_base', 'status', 'is_deleted'], name='knowledge_d_knowled_a25802_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['organization', 'checksum'], name='knowledge_d_organiz_383d1b_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('document', 'revision', 'position'), name='unique_document_chunk_revision_position'),
        ),
    ]
