# Generated by Django 5.2.17 on 2026-09-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial_compacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='scope',
            field=models.CharField(db_index=True, default='organization', max_length=30),
        ),
    ]
