import { useEffect, useState } from 'react';
import { Alert, Button, Input, InputNumber, Select, Tag } from 'antd';
import { productionFormats, type ProductionFormat } from '@/services/douyinBenchmark';
import { documentError } from '@/services/documents';
import type { CreatorProfile, Idea, ResearchClient, ResearchTask, ResearchVersion } from '@/services/douyinResearch';
import { allRows, DeleteRecord, Field, Pager, RecordEditor, Status, useRows, type EditorField } from './ResearchCommon';

const profileFields: EditorField[] = [{ key: 'name', label: '档案名称' }, ...Object.entries({ positioning: '账号定位', audience: '目标受众', experiences: '真实经历', products: '产品资料', voice: '表达习惯', conditions: '拍摄条件' }).map(([key, label]) => ({ key, label, kind: 'long' as const })), { key: 'is_default', label: '设为默认档案', kind: 'switch' }];
export function CreatorProfiles({ client }: { client: ResearchClient }) {
  const rows = useRows<CreatorProfile>(client, 'creator-profiles'); const [editing, setEditing] = useState<object | null>(null);
  return <section className="douyin-form"><div className="douyin-section-title"><h2>个人创作档案</h2><Button type="primary" onClick={() => setEditing({ name: '', is_default: rows.count === 0 })}>新建档案</Button></div><Status loading={rows.loading} error={rows.error} empty={!rows.results.length} /><div className="douyin-research-grid">{rows.results.map(profile => <article key={profile.id} className="douyin-research-card"><h3>{profile.name} {profile.is_default && <Tag>默认</Tag>}</h3><p>{profile.positioning}</p><p>{profile.audience}</p><div className="douyin-actions"><Button onClick={() => setEditing(profile)}>编辑档案</Button><DeleteRecord client={client} resource="creator-profiles" record={profile} done={rows.reload} /></div></article>)}</div><Pager rows={rows} />{editing && <RecordEditor title="创作档案" fields={profileFields} initial={editing} onClose={() => setEditing(null)} onSave={async values => { if (values.id) await client.update('creator-profiles', String(values.id), values); else await client.create('creator-profiles', values); rows.reload(); }} />}</section>;
}

export function CreationCenter({ client, initialIdea, run, onProfiles }: { client: ResearchClient; initialIdea: Idea | null; run: (body: Record<string, unknown>) => Promise<void>; onProfiles: () => void }) {
  const [profiles, setProfiles] = useState<CreatorProfile[]>([]); const [ideas, setIdeas] = useState<Idea[]>([]); const [tasks, setTasks] = useState<ResearchTask[]>([]); const [brands, setBrands] = useState<{ id: string; name: string }[]>([]);
  const [profileId, setProfileId] = useState(''); const [ideaId, setIdeaId] = useState(initialIdea?.id || ''); const [reference, setReference] = useState(''); const [brandId, setBrandId] = useState<string>();
  const [brief, setBrief] = useState({ positioning: '', audience: '', theme: initialIdea?.title || '', conditions: '', duration: 60, production_format: 'talking_head' as ProductionFormat });
  const [sourceTask, setSourceTask] = useState(''); const [versions, setVersions] = useState<ResearchVersion[]>([]); const [versionId, setVersionId] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { let alive = true; void Promise.all([allRows<CreatorProfile>(client, 'creator-profiles'), allRows<Idea>(client, 'ideas'), allRows<ResearchTask>(client, 'tasks'), client.editor.brands()]).then(([p, i, t, b]) => {
    if (!alive) return; setProfiles(p); setIdeas(i); setTasks(t); setBrands(b); const sourceAccount = t.find(task => task.id === initialIdea?.source_task)?.output.creation_context?.target_account_id; const def = (sourceAccount ? p.find(row => row.account === sourceAccount) : undefined) || p.find(row => row.is_default && !row.account); if (def) { setProfileId(def.id); setBrief(old => ({ ...old, positioning: def.positioning, audience: def.audience, conditions: def.conditions })); }
  }).catch(e => { if (alive) setError(documentError(e)); }); return () => { alive = false; }; }, [client, initialIdea?.source_task]);
  useEffect(() => { let alive = true; setVersions([]); setVersionId(''); if (sourceTask) void client.versions(sourceTask).then(rows => { if (alive) { setVersions(rows); setVersionId(rows[0]?.id || ''); } }).catch(e => { if (alive) setError(documentError(e)); }); return () => { alive = false; }; }, [client, sourceTask]);
  const selectedProfile = profiles.find(p => p.id === profileId);
  async function start(body: Record<string, unknown>) { setBusy(true); setError(''); try { await run(body); } catch (e) { setError(documentError(e)); } finally { setBusy(false); } }
  return <section className="douyin-form"><div className="douyin-section-title"><h2>创作中心</h2><Button onClick={onProfiles}>管理创作档案</Button></div>{error && <Alert type="error" message={error} />}{selectedProfile?.account && <p>当前账号档案：{selectedProfile.name} · 文风 {selectedProfile.active_version_number ? `v${selectedProfile.active_version_number}` : '尚未确认'}。定位与表达使用已确认版本；主题可留空。</p>}
    <div className="douyin-research-filters"><Field label="创作档案"><Select aria-label="创作档案" allowClear value={profileId || undefined} options={profiles.map(p => ({ value: p.id, label: p.account ? `${p.name} · 我的账号` : p.name }))} onChange={id => { setProfileId(id || ''); const p = profiles.find(row => row.id === id); setBrief(old => ({ ...old, positioning: p?.positioning || '', audience: p?.audience || '', conditions: p?.conditions || '', theme: '' })); setReference(''); setBrandId(undefined); setIdeaId(''); }} /></Field>
      <Field label="选题库"><Select aria-label="选题库" allowClear value={ideaId || undefined} options={ideas.map(i => ({ value: i.id, label: i.title }))} onChange={id => { setIdeaId(id || ''); const idea = ideas.find(i => i.id === id); if (idea) setBrief(old => ({ ...old, theme: idea.title })); }} /></Field>
      <Field label="参考研究"><Select aria-label="参考研究" allowClear value={reference || undefined} options={tasks.filter(t => ['breakdown', 'joint', 'radar', 'needs'].includes(t.kind) && t.status === 'succeeded').map(t => ({ value: t.id, label: `${t.kind} · ${new Date(t.created_at).toLocaleString()}` }))} onChange={id => setReference(id || '')} /></Field>
      <Field label="品牌定位与语气"><Select aria-label="品牌定位与语气" disabled={!!selectedProfile?.account} allowClear value={brandId} options={brands.map(b => ({ value: b.id, label: b.name }))} onChange={setBrandId} /></Field>
    </div>
    <div className="douyin-form-grid">{(['positioning', 'audience', 'theme', 'conditions'] as const).map(key => <Field key={key} label={{ positioning: '本次账号定位', audience: '本次目标受众', theme: '本次主题', conditions: '本次拍摄条件' }[key]}><Input.TextArea aria-label={key} rows={3} disabled={!!selectedProfile?.account && key !== 'theme'} maxLength={key === 'conditions' ? 3000 : 2000} value={brief[key]} onChange={e => setBrief({ ...brief, [key]: e.target.value })} /></Field>)}</div>
    <div className="douyin-actions"><Field label="视频形式"><Select aria-label="视频形式" value={brief.production_format} options={Object.entries(productionFormats).map(([value, option]) => ({ value, label: option.label }))} onChange={value => setBrief({ ...brief, production_format: value })} /></Field><Field label="目标时长（秒）"><InputNumber aria-label="目标时长（秒）" min={15} max={brief.production_format === 'animation' ? 120 : 600} value={brief.duration} onChange={value => setBrief({ ...brief, duration: value || 60 })} /></Field><Button type="primary" loading={busy} disabled={selectedProfile?.account ? !selectedProfile.active_version : !brief.positioning.trim() || !brief.theme.trim()} onClick={() => void start({ kind: 'topics', ...brief, ...(profileId && { profile_id: profileId }), ...(selectedProfile?.account && { target_account_id: selectedProfile.account }), ...(ideaId && { idea_id: ideaId }), ...(reference && { source_task_id: reference }), ...(brandId && { brand_profile_id: brandId }) })}>生成3个创作选题</Button></div>
    <hr /><h3>开头与标题实验室</h3><p>选择已保存的文案版本，生成候选开头、标题和封面短句。</p><div className="douyin-research-filters"><Field label="来源脚本或改写"><Select aria-label="来源脚本或改写" value={sourceTask || undefined} options={tasks.filter(t => ['script', 'rewrite'].includes(t.kind) && t.status === 'succeeded').map(t => ({ value: t.id, label: `${t.output.title || '文案'} · ${new Date(t.created_at).toLocaleString()}` }))} onChange={setSourceTask} /></Field><Field label="来源保存版本"><Select aria-label="来源保存版本" value={versionId || undefined} options={versions.map(v => ({ value: v.id, label: `版本${v.revision}` }))} onChange={setVersionId} /></Field></div><Button disabled={!versionId || busy} onClick={() => void start({ kind: 'variants', source_version_id: versionId })}>生成候选表达</Button>
  </section>;
}
