import { useEffect, useState } from 'react';
import { Alert, Button, Modal, Select } from 'antd';
import type { DouyinAccount } from '@/services/douyinBenchmark';
import { metric } from '@/services/douyinBenchmark';
import { documentError } from '@/services/documents';
import type { Idea, Publication, PublicationSummary, ResearchClient, ResearchTask, ResearchVersion, ResearchWork, Trend } from '@/services/douyinResearch';
import { allRows, DeleteRecord, Field, Pager, RecordEditor, Status, useRows } from './ResearchCommon';
import { TrendPanel } from './ResearchLibrary';

export function PublicationReview({ client, accounts, run, accountId = '', onAccount }: { accountId?: string; onAccount?: (id: string) => void; client: ResearchClient; accounts: DouyinAccount[]; reloadAccounts: () => void; run: (body: Record<string, unknown>) => Promise<void> }) {
  const rows = useRows<Publication>(client, 'publications', { account: accountId || undefined }); const [works, setWorks] = useState<ResearchWork[]>([]); const [ideas, setIdeas] = useState<Idea[]>([]); const [scripts, setScripts] = useState<ResearchTask[]>([]); const [versions, setVersions] = useState<ResearchVersion[]>([]);
  const [source, setSource] = useState(''); const [editing, setEditing] = useState<object | null>(null); const [error, setError] = useState(''); const [trend, setTrend] = useState<Trend | null>(null); const [busy, setBusy] = useState(false);
  const [summary, setSummary] = useState<PublicationSummary | null>(null); const [grouping, setGrouping] = useState<'by_theme' | 'by_expression'>('by_theme');
  useEffect(() => { let alive = true; void client.publicationSummary(accountId || undefined).then(data => { if (alive) setSummary(data); }).catch(e => { if (alive) setError(documentError(e)); }); return () => { alive = false; }; }, [client, rows.results, accountId]);
  useEffect(() => { let alive = true; void Promise.all([allRows<ResearchWork>(client, 'works'), allRows<Idea>(client, 'ideas'), allRows<ResearchTask>(client, 'tasks')]).then(([w, i, t]) => { if (alive) { setWorks(w); setIdeas(i); setScripts(t.filter(t => ['script', 'rewrite', 'article'].includes(t.kind) && (!accountId || t.output.creation_context?.target_account_id === accountId) && t.status === 'succeeded')); } }).catch(e => { if (alive) setError(documentError(e)); }); return () => { alive = false; }; }, [client, accounts, accountId]);
  useEffect(() => { let alive = true; setVersions([]); if (source) void client.versions(source).then(v => { if (alive) setVersions(v); }).catch(e => { if (alive) setError(documentError(e)); }); return () => { alive = false; }; }, [client, source]);
  async function action(fn: () => Promise<unknown>) { setBusy(true); setError(''); try { await fn(); rows.reload(); } catch (e) { setError(documentError(e)); } finally { setBusy(false); } }
  return <section className="douyin-form"><h2>自己的作品复盘</h2><p>“我的账号”为个人归类，不代表平台认证。仅使用 DTK 获取的公开互动数据，不推算播放量或完播率。</p>
    <Field label="复盘账号"><Select aria-label="复盘账号" value={accountId} onChange={onAccount} options={[{ value: '', label: '全部我的账号' }, ...accounts.filter(a => a.is_owned).map(a => ({ value: a.id, label: a.name || a.source_url }))]} /></Field>
    <Field label="关联的文案任务（可选）"><Select aria-label="关联的文案任务" allowClear value={source || undefined} onChange={v => setSource(v || '')} options={scripts.map(t => ({ value: t.id, label: `${t.output.title || '文案'} · ${new Date(t.created_at).toLocaleString()}` }))} /></Field>
    <div className="douyin-actions"><Button type="primary" onClick={() => setEditing({ work: '', title: '', theme: '', hook: '', notes: '', script_version: versions[0]?.id || null })}>关联已发布作品</Button><Button disabled={!rows.count || busy} onClick={() => void action(() => run({ kind: 'review', ...(accountId && { target_account_id: accountId }) }))}>生成复盘建议</Button></div>{error && <Alert type="error" message={error} />}<Status loading={rows.loading} error={rows.error} empty={!rows.results.length} />
    {summary && <section><Field label="分组比较"><Select aria-label="分组比较" value={grouping} onChange={setGrouping} options={[{ value: 'by_theme', label: '按主题' }, { value: 'by_expression', label: '按标题与开头' }]} /></Field><p>{summary.note}</p><div className="douyin-research-grid">{summary[grouping]?.map(g => <article className="douyin-research-card" key={g.label}><h3>{g.label}</h3><p>样本 {g.sample_count} 条 · 发布年龄 {g.age_days ? `${g.age_days[0]}–${g.age_days[1]}天` : '未获取'}</p><p>点赞中位数 {metric(g.medians.likes)} · 评论中位数 {metric(g.medians.comments)} · 收藏中位数 {metric(g.medians.collects)}</p></article>)}</div></section>}
    <div className="douyin-research-grid">{rows.results.map(p => <article key={p.id} className="douyin-research-card"><h3>{p.title || p.work_detail.title}</h3><p>主题：{p.theme || '未分类'}</p><p className="douyin-preserve-text">开头：{p.hook || '未记录'}</p><p>发布：{p.work_detail.published_at ? new Date(p.work_detail.published_at).toLocaleString() : '未获取'} · 采集：{new Date(p.work_detail.captured_at).toLocaleString()}</p>
      <dl className="douyin-research-metrics">{(['likes', 'comments', 'collects'] as const).map(key => <div key={key}><dt>{{ likes: '点赞', comments: '评论', collects: '收藏' }[key]}</dt><dd>{metric(p.work_detail[key])}</dd></div>)}</dl><div className="douyin-actions"><Button onClick={() => setEditing(p)}>编辑关联</Button><Button disabled={busy} onClick={() => void action(() => run({ kind: 'refresh', work_ids: [p.work], target_account_id: p.work_detail.account_id }))}>刷新数据</Button><Button onClick={() => void action(async () => setTrend(await client.trend(p.work)))}>增长趋势</Button><DeleteRecord client={client} resource="publications" record={p} done={rows.reload} /></div>
    </article>)}</div><Pager rows={rows} />
    {editing && <RecordEditor title="关联发布作品" initial={editing} fields={[
      { key: 'work', label: '我的账号已发布作品', kind: 'select', options: works.filter(w => w.is_owned && (!accountId || w.account_id === accountId)).map(w => ({ value: w.id, label: `${w.account_name} · ${w.title}` })) },
      { key: 'idea', label: '关联选题', kind: 'select', options: ideas.map(i => ({ value: i.id, label: i.title })) },
      { key: 'script_version', label: '关联文案版本', kind: 'select', options: versions.map(v => ({ value: v.id, label: `版本${v.revision} · ${v.content.title || '文案'}` })) },
      { key: 'theme', label: '主题分类' }, { key: 'title', label: '实际使用的标题' }, { key: 'hook', label: '实际使用的开头', kind: 'long' }, { key: 'notes', label: '复盘笔记', kind: 'long' },
    ]} onClose={() => setEditing(null)} onSave={async value => { if (value.id) await client.update('publications', String(value.id), value); else await client.create('publications', value); rows.reload(); }} />}
    <Modal className="douyin-modal" open={!!trend} title="作品增长趋势" footer={null} width={850} onCancel={() => setTrend(null)}>{trend && <TrendPanel data={trend} />}</Modal>
  </section>;
}
