import { useEffect, useState } from 'react';
import { Alert, Button, Select, Switch, Tabs, Tag } from 'antd';
import type { DouyinAccount } from '@/services/douyinBenchmark';
import { documentError } from '@/services/documents';
import { metricLabels, type Digest, type Notice, type ResearchClient, type ResearchWork, type Subscription } from '@/services/douyinResearch';
import { allRows, DeleteRecord, Field, Pager, RecordEditor, Status, useRows } from './ResearchCommon';

export function SubscriptionCenter({ client, accounts, openAccount, onTask }: { client: ResearchClient; accounts: DouyinAccount[]; openAccount: (id: string) => void; onTask: (id: string) => void }) {
  const [tab, setTab] = useState('subscriptions'); const [unread, setUnread] = useState(false); const [editing, setEditing] = useState<object | null>(null); const [works, setWorks] = useState<ResearchWork[]>([]); const [accountId, setAccountId] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const subscriptions = useRows<Subscription>(client, 'subscriptions'); const notices = useRows<Notice>(client, 'notifications', { unread }); const digests = useRows<Digest>(client, 'digests');
  useEffect(() => { let alive = true; void allRows<ResearchWork>(client, 'works').then(rows => { if (alive) setWorks(rows); }).catch(e => { if (alive) setError(documentError(e)); }); return () => { alive = false; }; }, [client]);
  async function action(fn: () => Promise<unknown>) { setBusy(true); setError(''); try { await fn(); subscriptions.reload(); notices.reload(); } catch (e) { setError(documentError(e)); } finally { setBusy(false); } }
  return <section className="douyin-form"><h2>订阅与通知</h2><p>开启后由后台刷新，无需保持页面打开；仅生成数据汇总，不自动调用 AI。日报于北京时间09:00汇总，有变化才生成。</p><Tabs activeKey={tab} onChange={setTab} items={[{ key: 'subscriptions', label: '账号订阅' }, { key: 'notifications', label: '应用内通知' }, { key: 'digests', label: '研究日报' }]} />{error && <Alert type="error" message={error} />}
    {tab === 'subscriptions' && <><div className="douyin-actions"><Field label="新增订阅账号"><Select aria-label="新增订阅账号" value={accountId || undefined} options={accounts.filter(a => !subscriptions.results.some(s => s.account === a.id)).map(a => ({ value: a.id, label: a.name || a.source_url }))} onChange={setAccountId} /></Field><Button type="primary" disabled={!accountId} onClick={() => setEditing({ account: accountId, enabled: false, interval_hours: 24, count: 50, tracked_works: [], percent: 50, likes: 100, comments: 20, collects: 20 })}>配置订阅</Button></div><Status loading={subscriptions.loading} error={subscriptions.error} empty={!subscriptions.results.length} />
      <div className="douyin-research-grid">{subscriptions.results.map(s => <article key={s.id} className="douyin-research-card"><h3>{accounts.find(a => a.id === s.account)?.name || '对标账号'}</h3><p>每 {s.interval_hours} 小时 · 采集 {s.count} 条 · 重点追踪 {s.tracked_works.length} 条</p><p>下次执行：{s.next_run_at ? new Date(s.next_run_at).toLocaleString() : '未启用'}</p>{s.blocked_reason && <Alert type="warning" message={s.blocked_reason} />}<div className="douyin-actions"><Switch aria-label="启用账号订阅" disabled={busy} checked={s.enabled} onChange={value => void action(() => client.update('subscriptions', s.id, { revision: s.revision, enabled: value }))} /><Button onClick={() => setEditing({ ...s, percent: 50, likes: 100, comments: 20, collects: 20, ...s.rules })}>调整订阅</Button><Button disabled={busy} onClick={() => void action(async () => onTask((await client.refresh(s.id)).id))}>立即刷新</Button><DeleteRecord client={client} resource="subscriptions" record={s} done={subscriptions.reload} /></div></article>)}</div><Pager rows={subscriptions} /></>}
    {tab === 'notifications' && <><Field label="仅显示未读"><Switch aria-label="仅显示未读" checked={unread} onChange={setUnread} /></Field><Status loading={notices.loading} error={notices.error} empty={!notices.results.length} />{notices.results.map(n => <article key={n.id} className="douyin-research-card"><h3>{n.title} {!n.read && <Tag color="blue">未读</Tag>}</h3><p>{new Date(n.created_at).toLocaleString()}</p><p>{n.body.message || n.body.title}</p>{n.kind === 'growth' && Object.entries(n.body.changes || {}).map(([key, value]) => <p key={key}>{metricLabels[key as keyof typeof metricLabels]}：{value.before} → {value.after}（+{value.delta}）</p>)}<div className="douyin-actions"><Button disabled={busy} onClick={() => void action(() => client.update('notifications', n.id, { revision: n.revision, read: !n.read }))}>{n.read ? '标为未读' : '标为已读'}</Button>{n.account && <Button onClick={() => openAccount(n.account!)}>查看来源账号</Button>}{n.kind === 'digest' && <Button onClick={() => setTab('digests')}>查看日报</Button>}</div></article>)}<Pager rows={notices} /></>}
    {tab === 'digests' && <><Status loading={digests.loading} error={digests.error} empty={!digests.results.length} />{digests.results.map(d => <article key={d.id} className="douyin-research-card"><h3>{d.day} 数据日报</h3><p>{new Date(d.body.from).toLocaleString()} 至 {new Date(d.body.to).toLocaleString()}</p><p>新作品 {d.body.new_works} · 增长提醒 {d.body.growth_alerts} · 采集异常 {d.body.errors}</p>{d.body.changes.map(change => <div key={change.work_id}><strong>{change.title}</strong><p>{Object.entries(change.delta).map(([key, value]) => `${metricLabels[key as keyof typeof metricLabels]} ${value >= 0 ? '+' : ''}${value}`).join(' · ')}</p></div>)}</article>)}<Pager rows={digests} /></>}
    {editing && <RecordEditor title="账号订阅设置" initial={editing} fields={[
      { key: 'enabled', label: '启用自动采集', kind: 'switch' }, { key: 'interval_hours', label: '刷新频率', kind: 'select', options: [6, 12, 24].map(value => ({ value, label: `每${value}小时` })) },
      { key: 'count', label: '每次主页采集数量', kind: 'select', options: [20, 50, 100].map(value => ({ value, label: `${value}条` })) },
      { key: 'tracked_works', label: '重点追踪作品（最多20条）', kind: 'multi', options: works.filter(w => w.account_id === (editing as { account: string }).account).map(w => ({ value: w.id, label: w.title })) },
      { key: 'percent', label: '最低增长百分比', kind: 'number', min: 0 }, ...Object.entries({ likes: '点赞最低增量', comments: '评论最低增量', collects: '收藏最低增量' }).map(([key, label]) => ({ key, label, kind: 'number' as const, min: 0 })),
    ]} onClose={() => setEditing(null)} onSave={async value => { const body = { ...value, rules: { percent: value.percent, likes: value.likes, comments: value.comments, collects: value.collects } }; if (value.id) await client.update('subscriptions', String(value.id), body); else await client.create('subscriptions', body); subscriptions.reload(); }} />}
  </section>;
}
