# Generated by Django 5.2.17 on 2026-09-18 12:49

import django.db.migrations.operations.special
import django.db.models.deletion
from importlib import import_module
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.templates.migrations.0003_alter_template_options_remove_template_description_and_more

_discard_legacy = import_module(
    "apps.templates.migrations.0003_alter_template_options_remove_template_description_and_more"
)

class Migration(migrations.Migration):

    atomic = False

    replaces = [('templates', '0001_initial'), ('templates', '0002_template_organization'), ('templates', '0003_alter_template_options_remove_template_description_and_more')]

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'template_categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('structure', models.JSONField(default=dict)),
                ('thumbnail', models.URLField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='templates.templatecategory')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='enterprise.organization')),
            ],
            options={
                'db_table': 'templates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('structure', models.JSONField(default=dict)),
                ('changelog', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='templates.template')),
            ],
            options={
                'db_table': 'template_versions',
                'ordering': ['-created_at'],
                'unique_together': {('template', 'version')},
            },
        ),
        migrations.RunPython(
            code=_discard_legacy.discard_legacy_template_data,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['-is_featured', '-updated_at']},
        ),
        migrations.RemoveField(
            model_name='template',
            name='description',
        ),
        migrations.RemoveField(
            model_name='template',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='template',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='template',
            name='usage_count',
        ),
        migrations.RemoveField(
            model_name='template',
            name='version',
        ),
        migrations.AddField(
            model_name='template',
            name='content_type',
            field=models.CharField(choices=[('article', '文章'), ('social_post', '社交媒体图文'), ('video_script', '短视频脚本'), ('brand_story', '品牌故事'), ('podcast', '播客文稿'), ('product_analysis', '产品分析'), ('other', '其他')], default='article', max_length=30),
        ),
        migrations.AddField(
            model_name='template',
            name='copyright_mode',
            field=models.CharField(choices=[('link_only', '仅保留链接'), ('excerpt', '摘要与引用'), ('authorized', '已获授权'), ('owned', '自有内容')], default='link_only', max_length=20),
        ),
        migrations.AddField(
            model_name='template',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='reading_time_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='recommended_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='reusable_patterns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='template',
            name='source_author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='template',
            name='source_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='source_excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='source_platform',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='template',
            name='source_published_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='source_snapshot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='source_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='template',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='template',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('review', '待审核'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='template',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='word_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TemplateAnalysisSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hook', '开头钩子'), ('conflict', '核心冲突'), ('structure', '内容结构'), ('technique', '表达技巧'), ('evidence', '论据与案例'), ('rhythm', '叙事节奏'), ('conversion', '转化设计'), ('reusable_pattern', '可复用点'), ('limitations', '适用边界'), ('other', '其他')], default='other', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('evidence_quote', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_sections', to='templates.template')),
            ],
            options={
                'db_table': 'template_analysis_sections',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='TemplateVersion',
        ),
    ]
