# Generated by Django 5.2.17 on 2026-10-10 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0008_membership_monthly_token_limit'),
        ('templates', '0001_initial_compacted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='source_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='template',
            name='source_kind',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='template',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='template',
            name='copyright_mode',
            field=models.CharField(choices=[('reference', '参考资料，授权未确认'), ('link_only', '仅保留链接'), ('excerpt', '摘要与引用'), ('authorized', '已获授权'), ('owned', '自有内容')], default='link_only', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('organization', 'created_by', 'source_kind', 'source_key'), name='template_source_once'),
        ),
    ]
