# Generated by Django 5.2.17 on 2026-09-22 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0007_compacted_0007_0008'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalRemoteConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('server_url', models.URLField(blank=True)),
                ('computer_name', models.CharField(default='我的电脑', max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('device_id', models.UUIDField(null=True)),
                ('credentials', models.TextField(blank=True)),
                ('pairing_code', models.CharField(blank=True, max_length=12)),
                ('pairing_expires_at', models.DateTimeField(null=True)),
                ('bound_account', models.CharField(blank=True, max_length=150)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='disabled', max_length=20)),
                ('connector_seen_at', models.DateTimeField(null=True)),
                ('local_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.organization')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('token_hash', models.CharField(max_length=64)),
                ('pairing_hash', models.CharField(max_length=64, null=True, unique=True)),
                ('pairing_expires_at', models.DateTimeField()),
                ('confirmed', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('session_id', models.CharField(blank=True, max_length=32)),
                ('last_seen_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
