# Generated by Django 5.2.17 on 2026-09-23 03:55

import apps.remote_access.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localremoteconfig',
            name='computer_name',
            field=models.CharField(default=apps.remote_access.models.default_computer_name, max_length=100),
        ),
    ]
