# Generated by Django 5.2.17 on 2026-09-18 12:58

import django.db.migrations.operations.special
from importlib import import_module
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.applications.migrations.0002_seed_default_chat

_seed_chat = import_module("apps.applications.migrations.0002_seed_default_chat")

class Migration(migrations.Migration):

    atomic = False

    replaces = [('applications', '0002_seed_default_chat'), ('applications', '0004_application_is_active_alter_application_slug_and_more'), ('applications', '0005_application_unique_global_application_slug_and_more')]

    dependencies = [
        ('agents', '0003_seed_general_agent'),
        ('applications', '0001_initial'),
        ('enterprise', '0005_external_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            code=_seed_chat.seed_default_chat,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='application',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_application_slug_per_org'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('slug',), name='unique_global_application_slug'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('slug',), name='unique_global_skill_slug'),
        ),
    ]
