# Generated by Django 5.0.1 on 2026-09-11 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_is_active_alter_application_slug_and_more'),
        ('enterprise', '0005_external_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('slug',), name='unique_global_application_slug'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('slug',), name='unique_global_skill_slug'),
        ),
    ]
