# Generated by Django 5.0.1 on 2026-09-11 10:45

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def _owner_organization(apps, owner):
    Organization = apps.get_model('enterprise', 'Organization')
    Membership = apps.get_model('enterprise', 'Membership')
    QuotaPolicy = apps.get_model('enterprise', 'QuotaPolicy')
    GovernancePolicy = apps.get_model('enterprise', 'GovernancePolicy')

    membership = Membership.objects.filter(
        user_id=owner.id, is_active=True).order_by('id').first()
    if membership is not None:
        return Organization.objects.get(pk=membership.organization_id)
    organization = Organization.objects.filter(owner_id=owner.id).order_by(
        'created_at').first()
    if organization is None:
        base = slugify(owner.username)[:70] or f'user-{owner.pk}'
        organization, _ = Organization.objects.get_or_create(
            slug=f'{base}-{owner.pk}',
            defaults={'name': f'{owner.username} Workspace', 'owner_id': owner.id},
        )
    Membership.objects.get_or_create(
        organization_id=organization.id, user_id=owner.id,
        defaults={'role': 'owner', 'is_active': True},
    )
    QuotaPolicy.objects.get_or_create(organization_id=organization.id)
    GovernancePolicy.objects.get_or_create(organization_id=organization.id)
    return organization


def create_chat_subtypes(apps, schema_editor):
    Application = apps.get_model('applications', 'Application')
    ChatApplication = apps.get_model('applications', 'ChatApplication')
    ChatApplication.objects.bulk_create([
        ChatApplication(application_id=application_id)
        for application_id in Application.objects.filter(
            kind='chat').values_list('id', flat=True)
    ])


def _chat_profile(application):
    ChatApplicationProfile = application._meta.apps.get_model(
        'applications', 'ChatApplicationProfile')
    profile = ChatApplicationProfile.objects.filter(
        application_id=application.id).first()
    if profile is None:
        return {
            'welcome_message': '',
            'input_placeholder': '',
            'empty_state_title': '',
            'allow_agent_selection': False,
            'allow_skill_selection': True,
            'allow_extra_skills': False,
            'conversation_policy': 'choose_history',
            'starter_layout': 'cards',
        }
    return {
        'welcome_message': profile.welcome_message,
        'input_placeholder': profile.input_placeholder,
        'empty_state_title': profile.empty_state_title,
        'allow_agent_selection': profile.allow_agent_selection,
        'allow_skill_selection': profile.allow_skill_selection,
        'allow_extra_skills': profile.allow_extra_skills,
        'conversation_policy': profile.conversation_policy,
        'starter_layout': profile.starter_layout,
    }


def _guided_prompts(application):
    result = []
    for prompt in application.guided_prompts.all().order_by('order', 'title'):
        questions = []
        for question in prompt.questions.all().order_by('order', 'id'):
            options = [{
                'id': str(option.id),
                'value': option.value,
                'label': option.label,
                'description': option.description,
                'icon': option.icon,
                'order': option.order,
            } for option in question.options.all().order_by('order', 'id')]
            questions.append({
                'id': str(question.id),
                'key': question.key,
                'label': question.label,
                'help_text': question.help_text,
                'type': question.type,
                'placeholder': question.placeholder,
                'required': question.required,
                'default_value': question.default_value,
                'validation': question.validation,
                'order': question.order,
                'options': options,
            })
        result.append({
            'id': str(prompt.id),
            'key': prompt.key,
            'title': prompt.title,
            'description': prompt.description,
            'icon': prompt.icon,
            'prompt_template': prompt.prompt_template,
            'action': prompt.action,
            'is_featured': prompt.is_featured,
            'order': prompt.order,
            'questions': questions,
        })
    return result


def migrate_application_definitions(apps, schema_editor):
    Application = apps.get_model('applications', 'Application')
    ApplicationDraft = apps.get_model('catalog', 'ApplicationDraft')

    for application in Application.objects.select_related(
            'created_by').all().iterator():
        organization_id = application.organization_id
        if organization_id is None:
            organization = _owner_organization(apps, application.created_by)
            organization_id = organization.id
            Application.objects.filter(pk=application.pk).update(
                organization_id=organization_id)

        default_config = application.default_config or {}
        is_chat = application.kind == 'chat'
        definition = {
            'kind': application.kind,
            'executor_kind': (
                'agent' if is_chat
                else default_config.get('executor_kind', 'media')
            ),
            'executor_key': (
                application.executor_key
                or ('agent-chat' if is_chat else application.slug)
            ),
            'executor_protocol_version': 1,
            'renderer_key': (
                application.renderer_key
                or ('chat' if is_chat else 'generic-task')
            ),
            'renderer_schema_version': 1,
            'retry_policy': default_config.get(
                'retry_policy', {'max_attempts': 3, 'retry_safe': True}),
            'input_schema': application.input_schema,
            'output_schema': application.output_schema,
            'default_config': default_config,
        }
        if is_chat:
            agent_bindings = [{
                'agent_id': binding.agent_id,
                'label': binding.label,
                'is_default': binding.is_default,
                'config_overrides': binding.config_overrides,
                'order': binding.order,
            } for binding in application.agent_bindings.all().order_by(
                'order', 'id')]
            if agent_bindings:
                default_index = next((
                    index for index, binding in enumerate(agent_bindings)
                    if binding['is_default']
                ), 0)
                for index, binding in enumerate(agent_bindings):
                    binding['is_default'] = index == default_index
            definition.update({
                'chat_profile': _chat_profile(application),
                'agent_bindings': agent_bindings,
                'skill_bindings': [{
                    'skill_id': str(binding.skill_id),
                    'mode': binding.mode,
                    'config': binding.config,
                    'order': binding.order,
                } for binding in application.skill_bindings.all().order_by(
                    'order', 'id')],
                'guided_prompts': _guided_prompts(application),
            })
        ApplicationDraft.objects.get_or_create(
            application_id=application.id,
            defaults={
                'organization_id': organization_id,
                'updated_by_id': application.created_by_id,
                'content': definition,
            },
        )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('applications', '0005_application_unique_global_application_slug_and_more'),
        ('agents', '0006_move_agent_definition_to_catalog'),
        ('catalog', '0001_initial'),
        ('enterprise', '0005_external_identity'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationskillbinding',
            name='unique_application_skill_binding',
        ),
        migrations.RemoveConstraint(
            model_name='guidedoption',
            name='unique_guided_option_value',
        ),
        migrations.RemoveConstraint(
            model_name='guidedprompt',
            name='unique_guided_prompt_key',
        ),
        migrations.RemoveConstraint(
            model_name='guidedquestion',
            name='unique_guided_question_key',
        ),
        migrations.CreateModel(
            name='ChatApplication',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chat_application', serialize=False, to='applications.application')),
            ],
            options={
                'db_table': 'chat_applications',
            },
        ),
        migrations.RunPython(create_chat_subtypes, migrations.RunPython.noop),
        migrations.RunPython(
            migrate_application_definitions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='applicationskillbinding',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationskillbinding',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='chatapplicationprofile',
            name='application',
        ),
        migrations.RemoveField(
            model_name='guidedoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='guidedprompt',
            name='application',
        ),
        migrations.RemoveField(
            model_name='guidedquestion',
            name='guided_prompt',
        ),
        migrations.RemoveField(
            model_name='application',
            name='default_config',
        ),
        migrations.RemoveField(
            model_name='application',
            name='executor_key',
        ),
        migrations.RemoveField(
            model_name='application',
            name='input_schema',
        ),
        migrations.RemoveField(
            model_name='application',
            name='output_schema',
        ),
        migrations.RemoveField(
            model_name='application',
            name='renderer_key',
        ),
        migrations.DeleteModel(
            name='ApplicationAgentBinding',
        ),
        migrations.DeleteModel(
            name='ApplicationSkillBinding',
        ),
        migrations.DeleteModel(
            name='ChatApplicationProfile',
        ),
        migrations.DeleteModel(
            name='GuidedOption',
        ),
        migrations.DeleteModel(
            name='GuidedPrompt',
        ),
        migrations.DeleteModel(
            name='GuidedQuestion',
        ),
    ]
