# Generated by Django 5.2.17 on 2026-09-18 12:52

import django.db.migrations.operations.special
import django.db.models.deletion
from importlib import import_module
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.applications.migrations.0006_chat_application_subtype
# apps.applications.migrations.0007_generalize_default_experience

_chat_subtypes = import_module(
    "apps.applications.migrations.0006_chat_application_subtype"
)
_generalize_defaults = import_module(
    "apps.applications.migrations.0007_generalize_default_experience"
)

class Migration(migrations.Migration):

    atomic = False

    replaces = [('applications', '0006_chat_application_subtype'), ('applications', '0007_generalize_default_experience'), ('applications', '0008_application_access_scope_application_allowed_users')]

    dependencies = [
        ('agents', '0006_move_agent_definition_to_catalog'),
        ('applications', '0005_application_unique_global_application_slug_and_more'),
        ('catalog', '0001_initial'),
        ('enterprise', '0005_external_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationskillbinding',
            name='unique_application_skill_binding',
        ),
        migrations.RemoveConstraint(
            model_name='guidedoption',
            name='unique_guided_option_value',
        ),
        migrations.RemoveConstraint(
            model_name='guidedprompt',
            name='unique_guided_prompt_key',
        ),
        migrations.RemoveConstraint(
            model_name='guidedquestion',
            name='unique_guided_question_key',
        ),
        migrations.CreateModel(
            name='ChatApplication',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chat_application', serialize=False, to='applications.application')),
            ],
            options={
                'db_table': 'chat_applications',
            },
        ),
        migrations.RunPython(
            code=_chat_subtypes.create_chat_subtypes,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=_chat_subtypes.migrate_application_definitions,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='applicationskillbinding',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationskillbinding',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='chatapplicationprofile',
            name='application',
        ),
        migrations.RemoveField(
            model_name='guidedoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='guidedprompt',
            name='application',
        ),
        migrations.RemoveField(
            model_name='guidedquestion',
            name='guided_prompt',
        ),
        migrations.RemoveField(
            model_name='application',
            name='default_config',
        ),
        migrations.RemoveField(
            model_name='application',
            name='executor_key',
        ),
        migrations.RemoveField(
            model_name='application',
            name='input_schema',
        ),
        migrations.RemoveField(
            model_name='application',
            name='output_schema',
        ),
        migrations.RemoveField(
            model_name='application',
            name='renderer_key',
        ),
        migrations.DeleteModel(
            name='ApplicationAgentBinding',
        ),
        migrations.DeleteModel(
            name='ApplicationSkillBinding',
        ),
        migrations.DeleteModel(
            name='ChatApplicationProfile',
        ),
        migrations.DeleteModel(
            name='GuidedOption',
        ),
        migrations.DeleteModel(
            name='GuidedPrompt',
        ),
        migrations.DeleteModel(
            name='GuidedQuestion',
        ),
        migrations.RunPython(
            code=_generalize_defaults.generalize_defaults,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='application',
            name='visibility',
            field=models.CharField(choices=[('private', '仅创建者'), ('restricted', '指定账号'), ('organization', '组织内全部账号')], db_index=True, default='private', max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicationAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', '查看者'), ('user', '使用者'), ('operator', '运维者'), ('editor', '编辑者')], default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='applications.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application_access_grants',
                'constraints': [models.UniqueConstraint(fields=('application', 'user'), name='unique_application_access_grant')],
            },
        ),
    ]
