# Generated by Django 5.2.17 on 2026-09-18 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_generalize_default_experience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='access_scope',
            field=models.CharField(choices=[('admin', '仅管理员'), ('restricted', '指定账号'), ('organization', '组织内全部账号')], db_index=True, default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
