# Generated by Django 5.2.17 on 2026-09-24 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0011_retire_contacts'),
        ('enterprise', '0008_membership_monthly_token_limit'),
        ('execution', '0006_compacted_0006_0007'),
        ('ideas_todos', '0004_memo_postgresql_rls'),
        ('online_documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('meeting', '会议'), ('interview', '访谈')], max_length=10)),
                ('recorded_on', models.DateField()),
                ('language', models.CharField(default='zh', max_length=10)),
                ('object_key', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField()),
                ('duration', models.FloatField(default=0)),
                ('segments', models.JSONField(default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('analysis_version', models.PositiveIntegerField(default=0)),
                ('analysis', models.JSONField(default=dict)),
                ('stage', models.CharField(default='queued', max_length=20)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='execution.run')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_recordings',
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160)),
                ('kind', models.CharField(max_length=20)),
                ('version', models.PositiveIntegerField()),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_documents.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='meeting_assistant.recording')),
            ],
            options={
                'db_table': 'meeting_exports',
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.PositiveSmallIntegerField(default=2)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('segment_ids', models.JSONField(default=list)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('todo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ideas_todos.todo')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='meeting_assistant.recording')),
            ],
            options={
                'db_table': 'meeting_actions',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['organization', 'application', 'owner'], name='meeting_record_scope'),
        ),
        migrations.AddConstraint(
            model_name='documentexport',
            constraint=models.UniqueConstraint(fields=('recording', 'key'), name='meeting_export_key'),
        ),
    ]
