# Generated by Django 5.2.17 on 2026-09-18 12:54

import django.db.migrations.operations.special
import django.db.models.deletion
import uuid
from importlib import import_module
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.enterprise.migrations.0002_seed_personal_organizations
# apps.enterprise.migrations.0004_seed_governance_policies

_personal_orgs = import_module(
    "apps.enterprise.migrations.0002_seed_personal_organizations"
)
_governance = import_module(
    "apps.enterprise.migrations.0004_seed_governance_policies"
)

class Migration(migrations.Migration):

    atomic = False

    replaces = [('enterprise', '0001_initial'), ('enterprise', '0002_seed_personal_organizations'), ('enterprise', '0003_governancepolicy_identityprovider_and_more'), ('enterprise', '0004_seed_governance_policies'), ('enterprise', '0005_external_identity')]

    dependencies = [
        ('users', '0002_alter_user_api_key_userapikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('target_type', models.CharField(default='agent', max_length=30)),
                ('target_id', models.CharField(blank=True, max_length=160)),
                ('evaluators', models.JSONField(blank=True, default=list)),
                ('quality_gate', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'evaluation_suites',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('embedding_provider', models.CharField(blank=True, max_length=100)),
                ('embedding_model', models.CharField(blank=True, max_length=160)),
                ('chunk_size', models.PositiveIntegerField(default=800)),
                ('chunk_overlap', models.PositiveIntegerField(default=100)),
                ('access_policy', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'knowledge_bases',
            },
        ),
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('target_version', models.CharField(blank=True, max_length=100)),
                ('score', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('passed', models.BooleanField(null=True)),
                ('results', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='enterprise.evaluationsuite')),
            ],
            options={
                'db_table': 'evaluation_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('input', models.JSONField(default=dict)),
                ('expected', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='enterprise.evaluationsuite')),
            ],
            options={
                'db_table': 'evaluation_cases',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('source_type', models.CharField(default='text', max_length=30)),
                ('source_uri', models.CharField(blank=True, max_length=1000)),
                ('content', models.TextField(blank=True)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('indexing', 'Indexing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='enterprise.knowledgebase')),
            ],
            options={
                'db_table': 'knowledge_documents',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='enterprise.organization'),
        ),
        migrations.AddField(
            model_name='evaluationsuite',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_suites', to='enterprise.organization'),
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('connector_type', models.CharField(max_length=80)),
                ('endpoint', models.CharField(blank=True, max_length=1000)),
                ('secret_ref', models.CharField(blank=True, max_length=200)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='enterprise.organization')),
            ],
            options={
                'db_table': 'connectors',
            },
        ),
        migrations.CreateModel(
            name='AutomationTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('trigger_type', models.CharField(default='webhook', max_length=30)),
                ('target_type', models.CharField(max_length=30)),
                ('target_id', models.CharField(max_length=160)),
                ('schedule', models.CharField(blank=True, max_length=120)),
                ('event_name', models.CharField(blank=True, max_length=160)),
                ('input_mapping', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_triggers', to='enterprise.organization')),
            ],
            options={
                'db_table': 'automation_triggers',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('resource_type', models.CharField(blank=True, db_index=True, max_length=120)),
                ('resource_id', models.CharField(blank=True, max_length=160)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='enterprise.organization')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(default='openai_compatible', max_length=50)),
                ('base_url', models.URLField(max_length=500)),
                ('secret_ref', models.CharField(blank=True, max_length=200)),
                ('available_models', models.JSONField(blank=True, default=list)),
                ('routing_weight', models.PositiveIntegerField(default=100)),
                ('timeout_seconds', models.PositiveIntegerField(default=120)),
                ('max_retries', models.PositiveIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='enterprise.organization')),
            ],
            options={
                'db_table': 'provider_configs',
            },
        ),
        migrations.CreateModel(
            name='QuotaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_token_limit', models.BigIntegerField(default=10000000)),
                ('monthly_cost_limit', models.DecimalField(decimal_places=4, default=1000, max_digits=14)),
                ('max_concurrent_runs', models.PositiveIntegerField(default=20)),
                ('requests_per_minute', models.PositiveIntegerField(default=120)),
                ('storage_bytes_limit', models.BigIntegerField(default=107374182400)),
                ('hard_limit', models.BooleanField(default=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota_policy', to='enterprise.organization')),
            ],
            options={
                'db_table': 'quota_policies',
            },
        ),
        migrations.CreateModel(
            name='RunTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(db_index=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('waiting', 'Waiting for input'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_traces', to='enterprise.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_traces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'run_traces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecretReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('backend', models.CharField(default='environment', max_length=30)),
                ('reference', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_references', to='enterprise.organization')),
            ],
            options={
                'db_table': 'secret_references',
            },
        ),
        migrations.CreateModel(
            name='TraceSpan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_span_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(default='internal', max_length=50)),
                ('status', models.CharField(default='running', max_length=20)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='enterprise.runtrace')),
            ],
            options={
                'db_table': 'trace_spans',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(db_index=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=160)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=160)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='success', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='enterprise.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usage_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='enterprise.knowledgedocument')),
            ],
            options={
                'db_table': 'knowledge_chunks',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('document', 'position'), name='unique_document_chunk_position')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('developer', 'Developer'), ('operator', 'Operator'), ('auditor', 'Auditor'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='enterprise.organization')),
            ],
            options={
                'db_table': 'organization_memberships',
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='unique_org_membership')],
            },
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_org_knowledge_base'),
        ),
        migrations.AddConstraint(
            model_name='providerconfig',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_org_provider'),
        ),
        migrations.AddConstraint(
            model_name='secretreference',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_org_secret_ref'),
        ),
        migrations.RunPython(
            code=_personal_orgs.seed_personal_organizations,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name='GovernancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retention_days', models.PositiveIntegerField(default=365)),
                ('redact_pii', models.BooleanField(default=True)),
                ('allowed_models', models.JSONField(blank=True, default=list)),
                ('blocked_terms', models.JSONField(blank=True, default=list)),
                ('allowed_tool_patterns', models.JSONField(blank=True, default=list)),
                ('blocked_tool_patterns', models.JSONField(blank=True, default=list)),
                ('require_tool_approval', models.BooleanField(default=True)),
                ('network_allowlist', models.JSONField(blank=True, default=list)),
                ('export_enabled', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='governance_policy', to='enterprise.organization')),
            ],
            options={
                'db_table': 'governance_policies',
            },
        ),
        migrations.CreateModel(
            name='IdentityProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('protocol', models.CharField(choices=[('oidc', 'OpenID Connect'), ('saml', 'SAML 2.0')], max_length=20)),
                ('issuer', models.CharField(max_length=500)),
                ('client_id', models.CharField(blank=True, max_length=300)),
                ('secret_ref', models.CharField(blank=True, max_length=200)),
                ('metadata_url', models.URLField(blank=True, max_length=1000)),
                ('domains', models.JSONField(blank=True, default=list)),
                ('claim_mapping', models.JSONField(blank=True, default=dict)),
                ('enforce_sso', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_providers', to='enterprise.organization')),
            ],
            options={
                'db_table': 'identity_providers',
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_org_identity_provider')],
            },
        ),
        migrations.RunPython(
            code=_governance.seed_governance,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=500)),
                ('claims', models.JSONField(blank=True, default=dict)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to='enterprise.organization')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='enterprise.identityprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'external_identities',
                'constraints': [models.UniqueConstraint(fields=('provider', 'subject'), name='unique_provider_subject')],
            },
        ),
    ]
