# Generated by Django 5.2.17 on 2026-09-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('enterprise', '0007_move_automation_trigger_state'), ('enterprise', '0008_remove_knowledgedocument_knowledge_base_and_more')]

    dependencies = [
        ('automations', '0001_initial'),
        ('enterprise', '0006_evaluation_run_execution'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='AutomationTrigger',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='knowledgedocument',
                    name='knowledge_base',
                ),
                migrations.RemoveField(
                    model_name='knowledgechunk',
                    name='document',
                ),
                migrations.DeleteModel(
                    name='KnowledgeBase',
                ),
                migrations.DeleteModel(
                    name='KnowledgeChunk',
                ),
                migrations.DeleteModel(
                    name='KnowledgeDocument',
                ),
            ],
        ),
    ]
