# Generated by Django 5.2.17 on 2026-09-17 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0007_move_automation_trigger_state'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='knowledgedocument', name='knowledge_base'),
                migrations.RemoveField(
                    model_name='knowledgechunk', name='document'),
                migrations.DeleteModel(name='KnowledgeBase'),
                migrations.DeleteModel(name='KnowledgeChunk'),
                migrations.DeleteModel(name='KnowledgeDocument'),
            ],
        ),
    ]
