# Generated by Django 5.2.17 on 2026-09-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0007_compacted_0007_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='monthly_token_limit',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
