# Generated by Django 5.2.17 on 2026-10-10 08:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0013_unify_conversation_catalog'),
        ('enterprise', '0008_membership_monthly_token_limit'),
        ('execution', '0008_run_command_steer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.JSONField(default=dict)),
                ('files', models.JSONField(default=dict)),
                ('coverage', models.JSONField(default=dict)),
                ('digest', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='repo_explainer.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('options', models.JSONField(default=dict)),
                ('output', models.JSONField(default=dict)),
                ('request_key', models.CharField(max_length=160)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='repo_explainer.project')),
                ('run', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repo_task', to='execution.run')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repo_explainer.snapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('draft', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='repo_explainer.project')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repo_explainer.task')),
                ('generation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='generated_content', to='repo_explainer.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('document', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='repo_explainer.content')),
            ],
            options={
                'ordering': ['-revision'],
            },
        ),
        migrations.CreateModel(
            name='Handoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('draft', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('request_key', models.CharField(max_length=160)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.application')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='repo_explainer.project')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repo_explainer.version')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('project', 'request_key'), name='repo_task_key'),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(fields=('content', 'revision'), name='repo_content_revision'),
        ),
        migrations.AddConstraint(
            model_name='handoff',
            constraint=models.UniqueConstraint(fields=('project', 'request_key'), name='repo_handoff_key'),
        ),
    ]
