# Generated by Django 5.2.17 on 2026-09-24 02:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0011_retire_contacts'),
        ('enterprise', '0008_membership_monthly_token_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriveEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240)),
                ('kind', models.CharField(choices=[('folder', 'Folder'), ('file', 'File')], max_length=10)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('media_type', models.CharField(blank=True, max_length=100)),
                ('object_key', models.CharField(blank=True, max_length=200)),
                ('trash_batch', models.UUIDField(blank=True, db_index=True, null=True)),
                ('trash_root', models.BooleanField(default=False)),
                ('purge_pending', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_drive.driveentry')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_drive.drivespace')),
            ],
        ),
        migrations.CreateModel(
            name='DriveUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240)),
                ('size', models.PositiveBigIntegerField()),
                ('last_modified', models.BigIntegerField(default=0)),
                ('offset', models.PositiveBigIntegerField(default=0)),
                ('chunk_size', models.PositiveIntegerField(default=8388608)),
                ('state', models.CharField(db_index=True, default='uploading', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_uploads', to='my_drive.driveentry')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='my_drive.driveentry')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_drive.drivespace')),
            ],
        ),
        migrations.CreateModel(
            name='DriveChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.PositiveBigIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='my_drive.driveupload')),
            ],
        ),
        migrations.AddConstraint(
            model_name='drivespace',
            constraint=models.UniqueConstraint(fields=('organization', 'owner'), name='drive_space_owner'),
        ),
        migrations.AddIndex(
            model_name='driveentry',
            index=models.Index(fields=['space', 'application', 'parent'], name='drive_entry_scope'),
        ),
        migrations.AddConstraint(
            model_name='drivechunk',
            constraint=models.UniqueConstraint(fields=('upload', 'offset'), name='drive_chunk_offset'),
        ),
    ]
