import { StudioSelect, StudioFilePicker } from './StudioControls';
import { useEffect, useState } from 'react';
import { Button } from 'antd';
import type { RunArtifact } from '@/services/applicationRuntime';
import { animationError, animationStatus, animationTerminal, type AnimationRun } from '@/services/animationStudio';
import { defaultExport, newScene, type Brand, type ExportOptions, type ImportedSheet, type LibraryAsset, type ProjectClient, type SpeechConfig, type StudioBatch, type StudioDocument, type StudioPreset, type TemplateField } from '@/services/animationProjects';

export function ExportFields({ value, onChange, doc }: { value: ExportOptions; onChange: (v: ExportOptions) => void; doc?: StudioDocument }) {
  return <div className="studio-fields"><label>格式<StudioSelect value={value.format} onChange={e => onChange({ ...value, format: e.target.value as ExportOptions['format'] })}>{['mp4', 'gif', 'png', 'srt', 'vtt'].map(v => <option key={v} value={v}>{v.toUpperCase()}</option>)}</StudioSelect></label>
    <label>清晰度<StudioSelect value={value.resolution} onChange={e => onChange({ ...value, resolution: Number(e.target.value) as 720 | 1080 })}><option value={1080}>1080p</option><option value={720}>720p</option></StudioSelect></label>
    <label>画质<StudioSelect value={value.quality} onChange={e => onChange({ ...value, quality: e.target.value as ExportOptions['quality'] })}><option value="standard">标准</option><option value="high">高清</option></StudioSelect></label>
    <label>封面时间（秒）<input type="number" min={0} step={1 / 30} value={value.cover_frame / 30} onChange={e => onChange({ ...value, cover_frame: Math.round(Number(e.target.value) * 30) })} /></label>
    {value.format === 'gif' && <><label>GIF 场景<StudioSelect value={value.scene_id || ''} onChange={e => onChange({ ...value, scene_id: e.target.value || undefined })}><option value="">从开头截取</option>{doc?.scenes?.map(s => <option key={s.id} value={s.id}>{s.title}</option>)}</StudioSelect></label><p>GIF 无声音，最长 15 秒，15 fps，长边 720px。</p></>}
  </div>;
}

export function AssetPanel({ client, assets, refresh, upload, onUse, report }: { client: ProjectClient; assets: LibraryAsset[]; refresh: () => Promise<void>; upload: (file: File) => Promise<void>; onUse: (item: LibraryAsset) => void; report: (e: unknown) => void }) {
  const [query, setQuery] = useState(''); const [preview, setPreview] = useState<{ url: string; type: string }>();
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview.url); }, [preview]);
  return <><label>搜索素材<input value={query} onChange={e => setQuery(e.target.value)} /></label><StudioFilePicker title="上传图片或音频" hint="图片 PNG / JPG / WEBP · 音频 MP3 / WAV / M4A" accept=".png,.jpg,.jpeg,.webp,.mp3,.wav,.m4a" onSelect={upload} onError={report} />
    {preview && (preview.type.startsWith('image/') ? <img className="studio-asset-preview" src={preview.url} alt="素材预览" /> : <audio src={preview.url} controls />)}
    {assets.filter(a => a.name.includes(query) || a.category.includes(query)).map(a => <article className="studio-card" key={a.id}><input aria-label="素材名称" defaultValue={a.name} onBlur={e => { if (e.target.value !== a.name) void client.asset(a.id, { name: e.target.value }).then(refresh).catch(report); }} /><input aria-label="素材分类" defaultValue={a.category} onBlur={e => { if (e.target.value !== a.category) void client.asset(a.id, { category: e.target.value }).then(refresh).catch(report); }} /><small>{a.duration === null ? '图片' : `${a.duration.toFixed(1)} 秒`} · {a.archived ? '已归档' : '可用'}</small><small>素材 ID：{a.id}</small><Button onClick={() => void navigator.clipboard.writeText(a.id).catch(report)}>复制素材 ID</Button><div className="studio-buttons"><Button onClick={() => void client.assetBlob(a.id).then(blob => setPreview({ url: URL.createObjectURL(blob), type: a.mime_type })).catch(report)}>预览</Button>{!a.archived && <Button onClick={() => onUse(a)}>添加到当前场景</Button>}<Button onClick={() => void client.asset(a.id, { archived: !a.archived }).then(refresh).catch(report)}>{a.archived ? '恢复' : '归档'}</Button></div></article>)}
  </>;
}

export function PresetPanel({ presets, doc, change, client, refresh, fonts, assets, report }: { presets: StudioPreset[]; doc: StudioDocument; change: (d: StudioDocument) => void; client: ProjectClient; refresh: () => Promise<void>; fonts: string[]; assets: LibraryAsset[]; report: (e: unknown) => void }) {
  const [name, setName] = useState(''); const [brand, setBrand] = useState<Brand>({ color: '#4f46e5', background: '#ffffff', font: 'Noto Sans SC', ending: '' });
  const [fields, setFields] = useState<TemplateField[]>([]);
  const apply = (p: StudioPreset) => {
    if (doc.scenes.some(s => s.locked)) { report(new Error('请先解锁场景，再应用模板或品牌。')); return; }
    if (p.kind === 'template' && p.data.document) change(structuredClone(p.data.document));
    else {
      const b = p.data; const scenes = doc.scenes.map(s => ({ ...s, style: { ...s.style, ...Object.fromEntries(Object.entries(b).filter(([k]) => ['color', 'background', 'font'].includes(k))) } }));
      if (b.ending) scenes.push({ ...newScene(), title: '感谢观看', body: b.ending, narration: '', frames: 150, style: { ...newScene().style, color: b.color || '#4f46e5', background: b.background || '#ffffff', font: b.font || 'Noto Sans SC' } });
      change({ ...doc, brand: b, scenes, subtitle_style: (b as Brand & { subtitle_style?: StudioDocument['subtitle_style'] }).subtitle_style || doc.subtitle_style });
    }
  };
  return <><h3>模板与品牌预设</h3><div className="studio-preset-list">{presets.map(p => <article className="studio-card" key={p.id}><strong>{p.name}</strong><small>{p.kind === 'template' ? '分镜模板' : '品牌预设'}</small><Button onClick={() => apply(p)}>应用到草稿</Button></article>)}</div>
    <label>预设名称<input value={name} onChange={e => setName(e.target.value)} /></label><h4>保存当前工程为模板</h4><Button onClick={() => setFields(doc.scenes.filter(s => !s.locked).map((s, i) => ({ name: `text${i + 1}`, scene_id: s.id, property: 'body', type: 'text' })))}>添加各场景正文为变量</Button>
    {fields.map((f, i) => <div className="studio-fields" key={i}><label>变量名<input value={f.name} onChange={e => setFields(v => v.map((x, j) => j === i ? { ...x, name: e.target.value } : x))} /></label><label>场景<StudioSelect value={f.scene_id} onChange={e => setFields(v => v.map((x, j) => j === i ? { ...x, scene_id: e.target.value } : x))}>{doc.scenes.filter(s => !s.locked).map(s => <option key={s.id} value={s.id}>{s.title}</option>)}</StudioSelect></label><label>字段<StudioSelect value={f.property} onChange={e => setFields(v => v.map((x, j) => j === i ? { ...x, property: e.target.value as TemplateField['property'], type: e.target.value === 'assets' ? 'image' : 'text' } : x))}><option value="body">正文</option><option value="title">标题</option><option value="narration">旁白</option><option value="assets">图片</option></StudioSelect></label><label>类型<StudioSelect value={f.type} onChange={e => setFields(v => v.map((x, j) => j === i ? { ...x, type: e.target.value as TemplateField['type'] } : x))}>{(f.property === 'assets' ? ['image'] : ['text', 'number']).map(t => <option key={t} value={t}>{{ text: '文字', number: '数字', image: '图片' }[t]}</option>)}</StudioSelect></label><Button onClick={() => setFields(v => v.filter((_, j) => j !== i))}>移除变量</Button></div>)}
    <Button disabled={!name.trim() || !doc.scenes.length} onClick={() => void client.preset({ kind: 'template', name, data: { document: doc, fields } }).then(refresh).catch(report)}>保存模板</Button>
    <h4>品牌设置</h4><div className="studio-fields"><label>品牌色<input type="color" value={brand.color} onChange={e => setBrand({ ...brand, color: e.target.value })} /></label><label>背景色<input type="color" value={brand.background} onChange={e => setBrand({ ...brand, background: e.target.value })} /></label><label>字体<StudioSelect value={brand.font} onChange={e => setBrand({ ...brand, font: e.target.value })}>{fonts.map(f => <option key={f}>{f}</option>)}</StudioSelect></label><label>Logo<StudioSelect value={brand.logo || ''} onChange={e => setBrand({ ...brand, logo: e.target.value })}><option value="">不添加</option>{assets.filter(a => a.duration === null && !a.archived).map(a => <option value={a.id} key={a.id}>{a.name}</option>)}</StudioSelect></label></div><label>片尾文字<textarea value={brand.ending} onChange={e => setBrand({ ...brand, ending: e.target.value })} /></label><Button disabled={!name.trim()} onClick={() => void client.preset({ kind: 'brand', name, data: { ...brand, subtitle_style: doc.subtitle_style } }).then(refresh).catch(report)}>保存品牌预设</Button>
  </>;
}

export function SpeechSettings({ client, report }: { client: ProjectClient; report: (e: unknown) => void }) {
  const [config, setConfig] = useState<SpeechConfig>(); const [saved, setSaved] = useState(false);
  useEffect(() => { let alive = true; void client.speech().then(v => { if (alive) setConfig(v); }).catch(report); return () => { alive = false; }; }, [client, report]);
  if (!config) return <p>正在加载配音配置…</p>;
  return <><h3>豆包配音配置</h3><p>组织管理员可保存配置。新版控制台使用 API Key，应用 ID 留空；旧版控制台填写应用 ID，并引用 Access Token。密钥通过组织设置中的秘密引用读取。</p><label><input type="checkbox" checked={config.enabled} onChange={e => setConfig({ ...config, enabled: e.target.checked })} />启用豆包配音</label>{[['app_id', '应用 ID（新版 API Key 留空）'], ['resource_id', '语音资源 ID'], ['secret_ref', '密钥引用名称']].map(([key, label]) => <label key={key}>{label}<input value={String(config[key as keyof SpeechConfig])} onChange={e => setConfig({ ...config, [key]: e.target.value })} /></label>)}
    {config.voices.map((v, i) => <div className="studio-fields" key={i}><label>音色名称<input value={v.name} onChange={e => setConfig({ ...config, voices: config.voices.map((x, j) => i === j ? { ...x, name: e.target.value } : x) })} /></label><label>音色 ID<input value={v.id} onChange={e => setConfig({ ...config, voices: config.voices.map((x, j) => i === j ? { ...x, id: e.target.value } : x) })} /></label><Button onClick={() => setConfig({ ...config, voices: config.voices.filter((_, j) => i !== j) })}>移除</Button></div>)}<Button onClick={() => setConfig({ ...config, voices: [...config.voices, { id: '', name: '' }] })}>添加音色</Button><Button type="primary" onClick={() => void client.saveSpeech(config).then(v => { setConfig(v); setSaved(true); }).catch(report)}>保存配置</Button>{saved && <p role="status">配置已保存</p>}</>;
}

export function BatchPanel({ client, presets, report, download }: { client: ProjectClient; presets: StudioPreset[]; report: (e: unknown) => void; download: (run: AnimationRun, artifact?: RunArtifact) => void }) {
  const templates = presets.filter(p => p.kind === 'template'); const [templateId, setTemplateId] = useState('');
  const template = templates.find(p => p.id === templateId); const fields = template?.data.fields || [];
  const [rows, setRows] = useState<Record<string, string>[]>([{}]); const [sheets, setSheets] = useState<ImportedSheet[]>([]); const [sheetIndex, setSheetIndex] = useState(0); const [mapping, setMapping] = useState<Record<string, string>>({});
  const [autoExport, setAutoExport] = useState(false); const [options, setOptions] = useState(defaultExport); const [batch, setBatch] = useState<StudioBatch>(); const [history, setHistory] = useState<{ id: string; status: string; count: number }[]>([]); const [busy, setBusy] = useState(false); const [validation, setValidation] = useState('');
  const [key, setKey] = useState(crypto.randomUUID());
  useEffect(() => { void client.batches().then(v => setHistory(v.results)).catch(report); }, [client, report, batch?.id]);
  useEffect(() => {
    if (!batch || animationTerminal(batch.run.status)) return;
    let alive = true; const timer = setInterval(() => { void client.getBatch(batch.id).then(v => { if (alive) setBatch(v); }).catch(report); }, 3000);
    return () => { alive = false; clearInterval(timer); };
  }, [batch, client, report]);
  const body = { template_id: templateId, rows, ...(autoExport ? { export_options: options } : {}) };
  const changed = () => { setValidation(''); setKey(crypto.randomUUID()); };
  return <><h3>批量制作</h3><label>模板<StudioSelect value={templateId} onChange={e => { setTemplateId(e.target.value); changed(); }}><option value="">选择模板</option>{templates.map(t => <option value={t.id} key={t.id}>{t.name}</option>)}</StudioSelect></label>
    <StudioFilePicker title="导入 CSV / XLSX" hint="支持 CSV、Excel 工作簿，导入后选择工作表并匹配字段" accept=".csv,.xlsx" onSelect={async file => { const v = await client.import(file); setSheets(v.sheets); setSheetIndex(0); setMapping({}); changed(); }} onError={report} />
    {sheets.length > 0 && <><label>工作表<StudioSelect value={sheetIndex} onChange={e => { setSheetIndex(Number(e.target.value)); setMapping({}); }}>{sheets.map((s, i) => <option key={s.name} value={i}>{s.name}</option>)}</StudioSelect></label>{fields.map(f => <label key={f.name}>{f.name} 对应列<StudioSelect value={mapping[f.name] || ''} onChange={e => setMapping({ ...mapping, [f.name]: e.target.value })}><option value="">选择列</option>{sheets[sheetIndex].columns.map(c => <option key={c}>{c}</option>)}</StudioSelect></label>)}<Button disabled={fields.some(f => !mapping[f.name])} onClick={() => { setRows(sheets[sheetIndex].rows.map(r => Object.fromEntries(fields.map(f => [f.name, r[mapping[f.name]] || ''])))); changed(); }}>载入表格</Button></>}
    <p>每批最多 100 条；图片字段填写素材库中的素材 ID。最多同时制作 2 条。</p><div className="studio-table-scroll"><table><thead><tr><th>序号</th>{fields.map(f => <th key={f.name}>{f.name}</th>)}<th>操作</th></tr></thead><tbody>{rows.map((r, i) => <tr key={i}><td>{i + 1}</td>{fields.map(f => <td key={f.name}><input aria-label={`第${i + 1}行 ${f.name}`} value={r[f.name] || ''} onChange={e => { setRows(v => v.map((x, j) => i === j ? { ...x, [f.name]: e.target.value } : x)); changed(); }} /></td>)}<td><Button onClick={() => { setRows(v => v.filter((_, j) => j !== i)); changed(); }}>删除</Button></td></tr>)}</tbody></table></div><Button disabled={rows.length >= 100} onClick={() => { setRows([...rows, {}]); changed(); }}>添加一行</Button>
    <label><input type="checkbox" checked={autoExport} onChange={e => { setAutoExport(e.target.checked); changed(); }} />生成后自动导出</label>{autoExport && <ExportFields value={options} onChange={v => { setOptions(v); changed(); }} doc={template?.data.document} />}
    <Button disabled={!template || !rows.length || busy} onClick={() => { setBusy(true); void client.batch({ ...body, validate_only: true }, key).then(() => setValidation('全部数据通过校验，可提交制作。')).catch(e => { const details = (e as { response?: { data?: { errors?: unknown } } }).response?.data?.errors; report(details ? new Error(JSON.stringify(details)) : e); }).finally(() => setBusy(false)); }}>校验数据</Button>{validation && <p role="status">{validation}</p>}
    <Button type="primary" disabled={!validation || busy} onClick={() => { setBusy(true); void client.batch(body, key).then(v => client.getBatch(v.id)).then(setBatch).catch(report).finally(() => setBusy(false)); }}>提交批量制作</Button>
    <label>历史批次<StudioSelect value={batch?.id || ''} onChange={e => { if (e.target.value) void client.getBatch(e.target.value).then(setBatch).catch(report); }}><option value="">选择批次</option>{history.map(h => <option key={h.id} value={h.id}>{h.count} 条 · {animationStatus(h.status)} · {h.id.slice(0, 8)}</option>)}</StudioSelect></label>
    {batch && <><p role="status">{animationStatus(batch.run.status)}</p>{batch.rows.map(r => <p key={r.index}>{r.index + 1}. {r.title} · {animationStatus(r.status)} {r.error}</p>)}<div className="studio-buttons">{!animationTerminal(batch.run.status) ? <Button onClick={() => void client.batchAction(batch.id, 'cancel', crypto.randomUUID()).then(() => client.getBatch(batch.id)).then(setBatch).catch(report)}>取消未完成项</Button> : <Button onClick={() => void client.batchAction(batch.id, 'retry', `retry-${batch.id}-${key}`).then(v => client.getBatch(v.id)).then(setBatch).catch(report)}>只重试失败项</Button>}{batch.run.artifacts.filter(a => a.kind === 'animation-batch').map(a => <Button key={a.id} onClick={() => download(batch.run, a)}>下载 {String(a.metadata.filename || '批次 ZIP')}</Button>)}</div></>}
  </>;
}

export function errorText(error: unknown) { return animationError(error); }
