# Generated by Django 5.2.17 on 2026-09-17 13:27

import app_center.study_with_method.backend.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0007_generalize_default_experience'),
        ('enterprise', '0008_remove_knowledgedocument_knowledge_base_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', '数学')], db_index=True, max_length=32)),
                ('grade_stage', models.CharField(choices=[('high_2', '高二')], db_index=True, max_length=32)),
                ('curriculum_version', models.CharField(db_index=True, max_length=120)),
                ('code', models.SlugField(max_length=180, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('node_type', models.CharField(choices=[('module', '模块'), ('chapter', '章节'), ('knowledge_point', '知识点')], max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='study_with_method.curriculumnode')),
            ],
            options={
                'db_table': 'study_curriculum_nodes',
                'ordering': ('subject', 'curriculum_version', 'order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', '数学')], db_index=True, max_length=32)),
                ('grade_stage', models.CharField(choices=[('high_2', '高二')], max_length=32)),
                ('source_image', models.FileField(blank=True, max_length=500, upload_to=app_center.study_with_method.backend.models.study_problem_upload_path)),
                ('original_text', models.TextField(blank=True)),
                ('confirmed_text', models.TextField(blank=True)),
                ('source', models.CharField(default='camera', max_length=32)),
                ('status', models.CharField(choices=[('needs_confirmation', '待确认'), ('ready', '可辅导'), ('completed', '已完成')], default='needs_confirmation', max_length=32)),
                ('max_hint_level', models.PositiveSmallIntegerField(default=0)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('answer_key', models.JSONField(blank=True, default=dict)),
                ('latest_run_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='study_with_method.curriculumnode')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
            ],
            options={
                'db_table': 'study_problems',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MistakeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', '数学')], db_index=True, max_length=32)),
                ('grade_stage', models.CharField(choices=[('high_2', '高二')], max_length=32)),
                ('cause', models.CharField(choices=[('concept', '概念不清'), ('formula', '公式遗忘'), ('reading', '审题错误'), ('calculation', '计算错误'), ('method', '方法选择'), ('careless', '粗心')], default='concept', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('mastery', models.PositiveSmallIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistakes', to='study_with_method.curriculumnode')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mistake', to='study_with_method.problem')),
            ],
            options={
                'db_table': 'study_mistakes',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='StudyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('daily_minutes', models.PositiveSmallIntegerField(default=45)),
                ('latest_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('target_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_profiles',
            },
        ),
        migrations.CreateModel(
            name='ReviewSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', '数学')], db_index=True, max_length=32)),
                ('grade_stage', models.CharField(choices=[('high_2', '高二')], max_length=32)),
                ('interval_step', models.PositiveSmallIntegerField(default=0)),
                ('next_review_at', models.DateTimeField(db_index=True)),
                ('last_result', models.CharField(blank=True, max_length=20)),
                ('completed_reviews', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mistake', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_schedule', to='study_with_method.mistakerecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_schedules', to='study_with_method.studyprofile')),
            ],
            options={
                'db_table': 'study_review_schedules',
                'ordering': ('next_review_at',),
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='study_with_method.studyprofile'),
        ),
        migrations.AddField(
            model_name='mistakerecord',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='study_with_method.studyprofile'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', '数学')], db_index=True, max_length=32)),
                ('grade_stage', models.CharField(choices=[('high_2', '高二')], max_length=32)),
                ('response', models.TextField(blank=True)),
                ('student_thought', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('hint_level_used', models.PositiveSmallIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='study_with_method.problem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='study_with_method.studyprofile')),
            ],
            options={
                'db_table': 'study_attempts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StudyWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled_subjects', models.JSONField(default=app_center.study_with_method.backend.models.default_enabled_subjects)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_workspace', to='applications.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
            ],
            options={
                'db_table': 'study_workspaces',
            },
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='study_with_method.studyworkspace'),
        ),
        migrations.CreateModel(
            name='SubjectEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', '数学')], db_index=True, max_length=32)),
                ('grade_stage', models.CharField(choices=[('high_2', '高二')], db_index=True, max_length=32)),
                ('curriculum_version', models.CharField(max_length=120)),
                ('current_chapter', models.CharField(max_length=160)),
                ('weak_topics', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='study_with_method.studyprofile')),
            ],
            options={
                'db_table': 'study_subject_enrollments',
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', '数学')], db_index=True, max_length=32)),
                ('grade_stage', models.CharField(choices=[('high_2', '高二')], max_length=32)),
                ('week_start', models.DateField(db_index=True)),
                ('metrics', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True)),
                ('next_week_advice', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='study_with_method.studyprofile')),
            ],
            options={
                'db_table': 'study_weekly_reports',
                'ordering': ('-week_start',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeMastery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', '数学')], db_index=True, max_length=32)),
                ('grade_stage', models.CharField(choices=[('high_2', '高二')], max_length=32)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='study_with_method.curriculumnode')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='study_with_method.studyprofile')),
            ],
            options={
                'db_table': 'study_knowledge_masteries',
                'constraints': [models.UniqueConstraint(fields=('profile', 'knowledge_point'), name='unique_study_knowledge_mastery')],
            },
        ),
        migrations.CreateModel(
            name='GuardianLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_guardian_study_links', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_study_links', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='study_with_method.studyprofile')),
            ],
            options={
                'db_table': 'study_guardian_links',
                'constraints': [models.UniqueConstraint(fields=('profile', 'guardian'), name='unique_study_guardian_link')],
            },
        ),
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', '数学')], db_index=True, max_length=32)),
                ('grade_stage', models.CharField(choices=[('high_2', '高二')], max_length=32)),
                ('task_type', models.CharField(choices=[('school_sync', '校内同步'), ('weak_point', '薄弱点训练'), ('review', '到期复习'), ('weekly_quiz', '周测')], max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('scheduled_for', models.DateField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=15)),
                ('status', models.CharField(choices=[('pending', '待完成'), ('completed', '已完成'), ('skipped', '已跳过')], db_index=True, default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='study_with_method.curriculumnode')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='study_with_method.studyprofile')),
            ],
            options={
                'db_table': 'study_tasks',
                'ordering': ('scheduled_for', 'created_at'),
                'constraints': [models.UniqueConstraint(fields=('profile', 'subject', 'scheduled_for', 'task_type', 'title'), name='unique_study_daily_task')],
            },
        ),
        migrations.AddConstraint(
            model_name='studyprofile',
            constraint=models.UniqueConstraint(fields=('workspace', 'student'), name='unique_study_profile_student'),
        ),
        migrations.AddConstraint(
            model_name='subjectenrollment',
            constraint=models.UniqueConstraint(fields=('profile', 'subject', 'grade_stage'), name='unique_study_subject_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='weeklyreport',
            constraint=models.UniqueConstraint(fields=('profile', 'subject', 'grade_stage', 'week_start'), name='unique_study_weekly_report'),
        ),
    ]
