# Generated by Django 5.2.17 on 2026-09-18 12:50

import app_center.study_with_method.backend.models
import django.db.migrations.operations.special
import django.db.models.deletion
import uuid
from importlib import import_module
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# app_center.study_with_method.backend.migrations.0002_postgresql_rls
# app_center.study_with_method.backend.migrations.0004_weekly_quiz_rls
# app_center.study_with_method.backend.migrations.0008_multi_subject_profiles

_base_rls = import_module(
    "app_center.study_with_method.backend.migrations.0002_postgresql_rls"
)
_quiz_rls = import_module(
    "app_center.study_with_method.backend.migrations.0004_weekly_quiz_rls"
)
_profiles = import_module(
    "app_center.study_with_method.backend.migrations.0008_multi_subject_profiles"
)

class Migration(migrations.Migration):

    atomic = False

    replaces = [('study_with_method', '0001_initial'), ('study_with_method', '0002_postgresql_rls'), ('study_with_method', '0003_studyprofile_grade_stage_and_more'), ('study_with_method', '0004_weekly_quiz_rls'), ('study_with_method', '0005_alter_curriculumnode_code'), ('study_with_method', '0006_mistakerecord_correct_answer_and_more'), ('study_with_method', '0007_problem_conversation'), ('study_with_method', '0008_multi_subject_profiles'), ('study_with_method', '0009_problem_source_attachment')]

    initial = True

    dependencies = [
        ('applications', '0007_generalize_default_experience'),
        ('conversations', '0011_backfill_supervisor_agent_conversations'),
        ('conversations', '0013_conversation_agent_locked'),
        ('enterprise', '0008_remove_knowledgedocument_knowledge_base_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', '数学')], db_index=True, max_length=32)),
                ('grade_stage', models.CharField(choices=[('high_2', '高二')], db_index=True, max_length=32)),
                ('curriculum_version', models.CharField(db_index=True, max_length=120)),
                ('code', models.SlugField(max_length=180, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('node_type', models.CharField(choices=[('module', '模块'), ('chapter', '章节'), ('knowledge_point', '知识点')], max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='study_with_method.curriculumnode')),
            ],
            options={
                'db_table': 'study_curriculum_nodes',
                'ordering': ('subject', 'curriculum_version', 'order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', '数学')], db_index=True, max_length=32)),
                ('grade_stage', models.CharField(choices=[('high_2', '高二')], max_length=32)),
                ('source_image', models.FileField(blank=True, max_length=500, upload_to=app_center.study_with_method.backend.models.study_problem_upload_path)),
                ('original_text', models.TextField(blank=True)),
                ('confirmed_text', models.TextField(blank=True)),
                ('source', models.CharField(default='camera', max_length=32)),
                ('status', models.CharField(choices=[('needs_confirmation', '待确认'), ('ready', '可辅导'), ('completed', '已完成')], default='needs_confirmation', max_length=32)),
                ('max_hint_level', models.PositiveSmallIntegerField(default=0)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('answer_key', models.JSONField(blank=True, default=dict)),
                ('latest_run_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='study_with_method.curriculumnode')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
            ],
            options={
                'db_table': 'study_problems',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MistakeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', '数学')], db_index=True, max_length=32)),
                ('grade_stage', models.CharField(choices=[('high_2', '高二')], max_length=32)),
                ('cause', models.CharField(choices=[('concept', '概念不清'), ('formula', '公式遗忘'), ('reading', '审题错误'), ('calculation', '计算错误'), ('method', '方法选择'), ('careless', '粗心')], default='concept', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('mastery', models.PositiveSmallIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistakes', to='study_with_method.curriculumnode')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mistake', to='study_with_method.problem')),
            ],
            options={
                'db_table': 'study_mistakes',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='StudyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('daily_minutes', models.PositiveSmallIntegerField(default=45)),
                ('latest_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('target_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_profiles',
            },
        ),
        migrations.CreateModel(
            name='ReviewSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', '数学')], db_index=True, max_length=32)),
                ('grade_stage', models.CharField(choices=[('high_2', '高二')], max_length=32)),
                ('interval_step', models.PositiveSmallIntegerField(default=0)),
                ('next_review_at', models.DateTimeField(db_index=True)),
                ('last_result', models.CharField(blank=True, max_length=20)),
                ('completed_reviews', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mistake', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_schedule', to='study_with_method.mistakerecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_schedules', to='study_with_method.studyprofile')),
            ],
            options={
                'db_table': 'study_review_schedules',
                'ordering': ('next_review_at',),
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='study_with_method.studyprofile'),
        ),
        migrations.AddField(
            model_name='mistakerecord',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='study_with_method.studyprofile'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', '数学')], db_index=True, max_length=32)),
                ('grade_stage', models.CharField(choices=[('high_2', '高二')], max_length=32)),
                ('response', models.TextField(blank=True)),
                ('student_thought', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('hint_level_used', models.PositiveSmallIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='study_with_method.problem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='study_with_method.studyprofile')),
            ],
            options={
                'db_table': 'study_attempts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StudyWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled_subjects', models.JSONField(default=app_center.study_with_method.backend.models.default_enabled_subjects)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_workspace', to='applications.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
            ],
            options={
                'db_table': 'study_workspaces',
            },
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='study_with_method.studyworkspace'),
        ),
        migrations.CreateModel(
            name='SubjectEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', '数学')], db_index=True, max_length=32)),
                ('grade_stage', models.CharField(choices=[('high_2', '高二')], db_index=True, max_length=32)),
                ('curriculum_version', models.CharField(max_length=120)),
                ('current_chapter', models.CharField(max_length=160)),
                ('weak_topics', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='study_with_method.studyprofile')),
            ],
            options={
                'db_table': 'study_subject_enrollments',
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', '数学')], db_index=True, max_length=32)),
                ('grade_stage', models.CharField(choices=[('high_2', '高二')], max_length=32)),
                ('week_start', models.DateField(db_index=True)),
                ('metrics', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True)),
                ('next_week_advice', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='study_with_method.studyprofile')),
            ],
            options={
                'db_table': 'study_weekly_reports',
                'ordering': ('-week_start',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeMastery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', '数学')], db_index=True, max_length=32)),
                ('grade_stage', models.CharField(choices=[('high_2', '高二')], max_length=32)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='study_with_method.curriculumnode')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='study_with_method.studyprofile')),
            ],
            options={
                'db_table': 'study_knowledge_masteries',
                'constraints': [models.UniqueConstraint(fields=('profile', 'knowledge_point'), name='unique_study_knowledge_mastery')],
            },
        ),
        migrations.CreateModel(
            name='GuardianLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_guardian_study_links', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_study_links', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='study_with_method.studyprofile')),
            ],
            options={
                'db_table': 'study_guardian_links',
                'constraints': [models.UniqueConstraint(fields=('profile', 'guardian'), name='unique_study_guardian_link')],
            },
        ),
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', '数学')], db_index=True, max_length=32)),
                ('grade_stage', models.CharField(choices=[('high_2', '高二')], max_length=32)),
                ('task_type', models.CharField(choices=[('school_sync', '校内同步'), ('weak_point', '薄弱点训练'), ('review', '到期复习'), ('weekly_quiz', '周测')], max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('scheduled_for', models.DateField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=15)),
                ('status', models.CharField(choices=[('pending', '待完成'), ('completed', '已完成'), ('skipped', '已跳过')], db_index=True, default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='study_with_method.curriculumnode')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='study_with_method.studyprofile')),
            ],
            options={
                'db_table': 'study_tasks',
                'ordering': ('scheduled_for', 'created_at'),
                'constraints': [models.UniqueConstraint(fields=('profile', 'subject', 'scheduled_for', 'task_type', 'title'), name='unique_study_daily_task')],
            },
        ),
        migrations.AddConstraint(
            model_name='studyprofile',
            constraint=models.UniqueConstraint(fields=('workspace', 'student'), name='unique_study_profile_student'),
        ),
        migrations.AddConstraint(
            model_name='subjectenrollment',
            constraint=models.UniqueConstraint(fields=('profile', 'subject', 'grade_stage'), name='unique_study_subject_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='weeklyreport',
            constraint=models.UniqueConstraint(fields=('profile', 'subject', 'grade_stage', 'week_start'), name='unique_study_weekly_report'),
        ),
        migrations.RunPython(
            code=_base_rls.enable_rls,
            reverse_code=_base_rls.disable_rls,
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='grade_stage',
            field=models.CharField(choices=[('high_2', '高二')], db_index=True, default='high_2', max_length=32),
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='primary_subject',
            field=models.CharField(choices=[('math', '数学')], db_index=True, default='math', max_length=32),
        ),
        migrations.CreateModel(
            name='WeeklyQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', '数学')], db_index=True, max_length=32)),
                ('grade_stage', models.CharField(choices=[('high_2', '高二')], max_length=32)),
                ('week_start', models.DateField(db_index=True)),
                ('questions', models.JSONField(default=list)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ready', '待完成'), ('completed', '已完成')], db_index=True, default='ready', max_length=20)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_quizzes', to='study_with_method.studyprofile')),
            ],
            options={
                'db_table': 'study_weekly_quizzes',
                'ordering': ('-week_start',),
                'constraints': [models.UniqueConstraint(fields=('profile', 'subject', 'grade_stage', 'week_start'), name='unique_study_weekly_quiz')],
            },
        ),
        migrations.RunPython(
            code=_quiz_rls.enable_rls,
            reverse_code=_quiz_rls.disable_rls,
        ),
        migrations.AlterField(
            model_name='curriculumnode',
            name='code',
            field=models.CharField(max_length=180, unique=True),
        ),
        migrations.AddField(
            model_name='mistakerecord',
            name='correct_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mistakerecord',
            name='knowledge_summary',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mistakerecord',
            name='similar_problem_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='problem',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_problems', to='conversations.conversation'),
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='focus_subjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='last_tutor_subject',
            field=models.CharField(blank=True, choices=[('chinese', '语文'), ('math', '数学'), ('english', '英语'), ('physics', '物理'), ('chemistry', '化学'), ('biology', '生物'), ('politics', '思想政治'), ('history', '历史'), ('geography', '地理')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='subjectenrollment',
            name='latest_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subjectenrollment',
            name='target_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='subjectenrollment',
            name='curriculum_version',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='subjectenrollment',
            name='current_chapter',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.RunPython(
            code=_profiles.migrate_profile_data,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='studyprofile',
            name='primary_subject',
            field=models.CharField(choices=[('chinese', '语文'), ('math', '数学'), ('english', '英语'), ('physics', '物理'), ('chemistry', '化学'), ('biology', '生物'), ('politics', '思想政治'), ('history', '历史'), ('geography', '地理')], db_index=True, default='math', max_length=32),
        ),
        migrations.AlterField(
            model_name='studyprofile',
            name='grade_stage',
            field=models.CharField(choices=[('high_1', '高一'), ('high_2', '高二'), ('high_3', '高三')], db_index=True, default='high_2', max_length=32),
        ),
        migrations.AlterField(
            model_name='subjectenrollment',
            name='subject',
            field=models.CharField(choices=[('chinese', '语文'), ('math', '数学'), ('english', '英语'), ('physics', '物理'), ('chemistry', '化学'), ('biology', '生物'), ('politics', '思想政治'), ('history', '历史'), ('geography', '地理')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='subjectenrollment',
            name='grade_stage',
            field=models.CharField(choices=[('high_1', '高一'), ('high_2', '高二'), ('high_3', '高三')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='curriculumnode',
            name='subject',
            field=models.CharField(choices=[('chinese', '语文'), ('math', '数学'), ('english', '英语'), ('physics', '物理'), ('chemistry', '化学'), ('biology', '生物'), ('politics', '思想政治'), ('history', '历史'), ('geography', '地理')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='curriculumnode',
            name='grade_stage',
            field=models.CharField(choices=[('high_1', '高一'), ('high_2', '高二'), ('high_3', '高三')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='curriculumnode',
            name='code',
            field=models.CharField(max_length=180),
        ),
        migrations.AddConstraint(
            model_name='curriculumnode',
            constraint=models.UniqueConstraint(fields=('subject', 'grade_stage', 'curriculum_version', 'code'), name='unique_study_curriculum_node'),
        ),
        migrations.AlterField(
            model_name='studytask',
            name='subject',
            field=models.CharField(choices=[('chinese', '语文'), ('math', '数学'), ('english', '英语'), ('physics', '物理'), ('chemistry', '化学'), ('biology', '生物'), ('politics', '思想政治'), ('history', '历史'), ('geography', '地理')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='studytask',
            name='grade_stage',
            field=models.CharField(choices=[('high_1', '高一'), ('high_2', '高二'), ('high_3', '高三')], max_length=32),
        ),
        migrations.AlterField(
            model_name='problem',
            name='subject',
            field=models.CharField(choices=[('chinese', '语文'), ('math', '数学'), ('english', '英语'), ('physics', '物理'), ('chemistry', '化学'), ('biology', '生物'), ('politics', '思想政治'), ('history', '历史'), ('geography', '地理')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='problem',
            name='grade_stage',
            field=models.CharField(choices=[('high_1', '高一'), ('high_2', '高二'), ('high_3', '高三')], max_length=32),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='subject',
            field=models.CharField(choices=[('chinese', '语文'), ('math', '数学'), ('english', '英语'), ('physics', '物理'), ('chemistry', '化学'), ('biology', '生物'), ('politics', '思想政治'), ('history', '历史'), ('geography', '地理')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='grade_stage',
            field=models.CharField(choices=[('high_1', '高一'), ('high_2', '高二'), ('high_3', '高三')], max_length=32),
        ),
        migrations.AlterField(
            model_name='mistakerecord',
            name='subject',
            field=models.CharField(choices=[('chinese', '语文'), ('math', '数学'), ('english', '英语'), ('physics', '物理'), ('chemistry', '化学'), ('biology', '生物'), ('politics', '思想政治'), ('history', '历史'), ('geography', '地理')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='mistakerecord',
            name='grade_stage',
            field=models.CharField(choices=[('high_1', '高一'), ('high_2', '高二'), ('high_3', '高三')], max_length=32),
        ),
        migrations.AlterField(
            model_name='mistakerecord',
            name='cause',
            field=models.CharField(choices=[('concept', '概念不清'), ('formula', '公式遗忘'), ('memory', '记忆不牢'), ('reading', '审题错误'), ('calculation', '计算错误'), ('method', '方法选择'), ('expression', '表达不规范'), ('experiment', '实验分析'), ('careless', '粗心')], default='concept', max_length=32),
        ),
        migrations.AlterField(
            model_name='reviewschedule',
            name='subject',
            field=models.CharField(choices=[('chinese', '语文'), ('math', '数学'), ('english', '英语'), ('physics', '物理'), ('chemistry', '化学'), ('biology', '生物'), ('politics', '思想政治'), ('history', '历史'), ('geography', '地理')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='reviewschedule',
            name='grade_stage',
            field=models.CharField(choices=[('high_1', '高一'), ('high_2', '高二'), ('high_3', '高三')], max_length=32),
        ),
        migrations.AlterField(
            model_name='knowledgemastery',
            name='subject',
            field=models.CharField(choices=[('chinese', '语文'), ('math', '数学'), ('english', '英语'), ('physics', '物理'), ('chemistry', '化学'), ('biology', '生物'), ('politics', '思想政治'), ('history', '历史'), ('geography', '地理')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='knowledgemastery',
            name='grade_stage',
            field=models.CharField(choices=[('high_1', '高一'), ('high_2', '高二'), ('high_3', '高三')], max_length=32),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='subject',
            field=models.CharField(choices=[('chinese', '语文'), ('math', '数学'), ('english', '英语'), ('physics', '物理'), ('chemistry', '化学'), ('biology', '生物'), ('politics', '思想政治'), ('history', '历史'), ('geography', '地理')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='grade_stage',
            field=models.CharField(choices=[('high_1', '高一'), ('high_2', '高二'), ('high_3', '高三')], max_length=32),
        ),
        migrations.AlterField(
            model_name='weeklyquiz',
            name='subject',
            field=models.CharField(choices=[('chinese', '语文'), ('math', '数学'), ('english', '英语'), ('physics', '物理'), ('chemistry', '化学'), ('biology', '生物'), ('politics', '思想政治'), ('history', '历史'), ('geography', '地理')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='weeklyquiz',
            name='grade_stage',
            field=models.CharField(choices=[('high_1', '高一'), ('high_2', '高二'), ('high_3', '高三')], max_length=32),
        ),
        migrations.AddField(
            model_name='problem',
            name='source_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_problems', to='conversations.messageattachment'),
        ),
    ]
