# Generated by Django 5.2.17 on 2026-09-17 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0008_remove_knowledgedocument_knowledge_base_and_more'),
        ('study_with_method', '0002_postgresql_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprofile',
            name='grade_stage',
            field=models.CharField(choices=[('high_2', '高二')], db_index=True, default='high_2', max_length=32),
        ),
        migrations.AddField(
            model_name='studyprofile',
            name='primary_subject',
            field=models.CharField(choices=[('math', '数学')], db_index=True, default='math', max_length=32),
        ),
        migrations.CreateModel(
            name='WeeklyQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', '数学')], db_index=True, max_length=32)),
                ('grade_stage', models.CharField(choices=[('high_2', '高二')], max_length=32)),
                ('week_start', models.DateField(db_index=True)),
                ('questions', models.JSONField(default=list)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ready', '待完成'), ('completed', '已完成')], db_index=True, default='ready', max_length=20)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_quizzes', to='study_with_method.studyprofile')),
            ],
            options={
                'db_table': 'study_weekly_quizzes',
                'ordering': ('-week_start',),
                'constraints': [models.UniqueConstraint(fields=('profile', 'subject', 'grade_stage', 'week_start'), name='unique_study_weekly_quiz')],
            },
        ),
    ]
