# Generated by Django 5.2.17 on 2026-09-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_with_method', '0004_weekly_quiz_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumnode',
            name='code',
            field=models.CharField(max_length=180, unique=True),
        ),
    ]
