# Generated by Django 5.2.17 on 2026-09-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_with_method', '0005_alter_curriculumnode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistakerecord',
            name='correct_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mistakerecord',
            name='knowledge_summary',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mistakerecord',
            name='similar_problem_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
