# Generated by Django 5.2.17 on 2026-09-17 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0011_backfill_supervisor_agent_conversations'),
        ('study_with_method', '0006_mistakerecord_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_problems', to='conversations.conversation'),
        ),
    ]
