# Generated by Django 5.2.17 on 2026-10-10 03:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0013_unify_conversation_catalog'),
        ('enterprise', '0008_membership_monthly_token_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.TextField()),
                ('parent', models.TextField()),
                ('kind', models.CharField(max_length=12)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('modified_at', models.DateTimeField(null=True)),
                ('identity', models.JSONField(default=dict)),
                ('cleanable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CleanerHost',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('heartbeat_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CleanerPreview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_ids', models.JSONField(default=list)),
                ('total_bytes', models.PositiveBigIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CleanerTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(db_index=True, max_length=64)),
                ('kind', models.CharField(max_length=12)),
                ('state', models.CharField(db_index=True, default='queued', max_length=16)),
                ('request_key', models.CharField(max_length=160)),
                ('parameters', models.JSONField(default=dict)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('processed', models.PositiveBigIntegerField(default=0)),
                ('total_bytes', models.PositiveBigIntegerField(default=0)),
                ('skipped', models.PositiveBigIntegerField(default=0)),
                ('deleted_bytes', models.PositiveBigIntegerField(default=0)),
                ('free_before', models.JSONField(default=dict)),
                ('free_after', models.JSONField(default=dict)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('heartbeat_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('preview', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleanup', to='disk_cleaner.cleanerpreview')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disk_cleaner.cleanertask')),
            ],
        ),
        migrations.CreateModel(
            name='CleanerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='pending', max_length=12)),
                ('reason', models.TextField(blank=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disk_cleaner.cleanerentry')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='disk_cleaner.cleanertask')),
            ],
        ),
        migrations.AddField(
            model_name='cleanerpreview',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disk_cleaner.cleanertask'),
        ),
        migrations.AddField(
            model_name='cleanerentry',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='disk_cleaner.cleanertask'),
        ),
        migrations.AddConstraint(
            model_name='cleanertask',
            constraint=models.UniqueConstraint(fields=('organization', 'application', 'owner', 'host', 'request_key'), name='cleaner_request_key'),
        ),
        migrations.AddConstraint(
            model_name='cleanerresult',
            constraint=models.UniqueConstraint(fields=('task', 'entry'), name='cleaner_result_entry'),
        ),
    ]
