# Generated by Django 5.2.17 on 2026-09-18 12:46

import django.db.models.deletion
import uuid
from importlib import import_module
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# app_center.contacts.backend.migrations.0002_postgresql_rls

_rls = import_module(
    "app_center.contacts.backend.migrations.0002_postgresql_rls"
)

class Migration(migrations.Migration):

    replaces = [('contacts', '0001_initial'), ('contacts', '0002_postgresql_rls')]

    initial = True

    dependencies = [
        ('applications', '0006_chat_application_subtype'),
        ('enterprise', '0005_external_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='企业通讯录', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_book', to='applications.application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
            ],
            options={
                'db_table': 'address_books',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('company', models.CharField(blank=True, db_index=True, max_length=160)),
                ('department', models.CharField(blank=True, db_index=True, max_length=160)),
                ('job_title', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('avatar', models.URLField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contacts.addressbook')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contacts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enterprise.organization')),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('phone', '电话'), ('email', '邮箱'), ('wechat', '微信'), ('other', '其他')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=40)),
                ('value', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='contacts.contact')),
            ],
            options={
                'db_table': 'contact_methods',
                'ordering': ['kind', '-is_primary', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'address_book', 'deleted_at'], name='contact_org_book_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactmethod',
            constraint=models.UniqueConstraint(fields=('contact', 'kind', 'value'), name='unique_contact_method_value'),
        ),
        migrations.AddConstraint(
            model_name='contactmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('contact', 'kind'), name='unique_primary_contact_method'),
        ),
        migrations.RunPython(
            code=_rls.enable_rls,
            reverse_code=_rls.disable_rls,
        ),
    ]
